### PR TITLE
Say "Open" not "Open Shared Grain" in emails

### PR DESCRIPTION
**Pull request by paulproteus**
See also: #1986

Curious for thoughts from @neynah @jacksingleton @zarvox and anyone else. Seems like an easy and satisfying change to me.

### CODE REVIEW

**Comment by zarvox** [comment]
Actually, I wanted the button to say "Open &lt;grainTitle&gt;" but GitHub swallowed the tag in the initial writing, and you only read the email, so you didn't see the edit that corrected it.

**Comment by zarvox** [comment]
Other options include "Open on Sandstorm" or "Open on ${serverTitle}".

**Comment by paulproteus** [comment]
> Open `<grainTitle>`

hah, oops!

I do honestly think that "Open" is better than "Open on {{serverTitle}}", and "Open {{grainTitle}}" has the downside that my typical grain titles of 15 words would make that button sort of ridiculous. I'm fine tabling this pull request until tomorrow, though, during blur day.

**Comment by zarvox** [comment]
If your typical grain title is 15 words, that's going to overflow the subject line (and all other pieces of UI) no matter where you put it.  I'm not sure that should be considered Sandstorm's problem; in fact, I think we should have affordances that encourage people to choose short, meaningful titles for grains, which are helpful in various contexts (referring to a grain title out loud, visibility in the grain list, etc.).  I am curious if there are things Sandstorm could do that would help make shorter titles more viable for your workflows, or why you choose such long titles today!

I particularly like adding the context about what is being opened or where this button will take you because I believe it's particularly valuable to add context for users who are first discovering Sandstorm through this invitation email.  For comparison, Google Docs' invitation emails read "Open in Docs".

I do feel pretty strongly that adding some context, be it grain-specific or service-specific, is better than just the bare string "Open", especially keeping in mind that we learned "people can't reliably tell open-the-noun from open-the-verb" from previous usertests back when the "Apps" and "Grains" navbar items were labeled "New" and "Open".

**Comment by paulproteus** [comment]
@zarvox all very sensible concerns. I'll think about it more and close this to avoid confusion, but happy to see more discussion here or on #1986

**Comment by neynah** [comment]
The subject line currently contains the grain title. If we want to provide additional context for people opening this grain, we can display the grain title again in the e-mail itself and have a button that just says "Open" or "Open in Sandstorm". The problem with "Open in Sandstorm" is that we provide no information as to what Sandstorm is.

E.g. Nena Nguyen is inviting you to collaborate on {{grainTitle}}. "Open" button.

FWIW, button strings are often relatively short in length whether they provided additional context or not. I think this is good practice. If we did display the grain title in the button itself we should decide on a max-width and cut off the text. Typically, long strings or text that will vary significantly in length should be displayed in full outside of the button. Looking through Google Drive's buttons, I haven't seen one that displays the document titles within the buttons themselves. Also, wetransfer's emails display the sender, the sender's message, the file name as well as a button that says "Download". The button string doesn't need to be long as the body of the email should provide more context about what is being "Opened" or "Downloaded".

(This issue closed halfway through me writing this but I'm deciding to post it anyway.)

**Pull request closed without merging**
