### PR TITLE
ACME: don't request cert for baseHost if covered by wildcard.

### LINKED ISSUE #3375: Can't fetch certificate, Sandstorm uses redundant domains in the request
I have a server that is running Sandstorm, but where the Sandstorm interface is not on the root domain, but on the sandstorm subdomain. When trying to fetch a certificate, it will however try to fetch a certificate for both the wildcard subdomain and the sandstorm subdomain, the second of which is obviously redundant. As a result, the request will fail with the following error:
```
[400] Error creating new order :: Domain name "sandstorm.<DOMAIN>" is redundant with a wildcard domain in the same request. Remove one or the other from the certificate request. [couldnt_renew_cert]
```

Looking at the ACME.js log, we can see that it indeed orders a certificate for both domains:
```
ACME.js notification: certificate_order {
  account: {
    key: { kid: 'https://acme-v02.api.letsencrypt.org/acme/acct/<ID>' }
  },
  subject: 'sandstorm.<DOMAIN>',
  altnames: [ 'sandstorm.<DOMAIN>', '*.<DOMAIN>' ],
  challengeTypes: [ 'dns-01' ]
}
```

Is there any way to fix this, or is this an issue with Sandstorm?

### PR DESCRIPTION
**Pull request by zenhack**
Fixes #3375

Note that I haven't actually tested this; we should of course do that before merging. I really wish we had automated tests for the acme stuff...

@Phaen, would you be up for building this branch and testing on your setup?

### CODE REVIEW

**Comment by Phaen** [comment]
I'm currently too busy to look into building Sandstorm from source myself
(plus I'm about to go to sleep). So it'll take a little while before I can
get to that. I hope someone else can carry that burden instead?

**Comment by ocdtrekkie** [comment]
Building from source would net you the ability to fix this "now", so if you are looking to resolve this quickly, it's a decent option. But assuming the fix doesn't break everything, it will likely be in the next release of Sandstorm, which should be soon (since they're roughly monthly).

**Comment by zenhack** [comment]
I just pushed another commit that will cause CI to upload the build as an artifact, which you can download and install rather than having to build from source. If you're willing to test, once the build is finished running you can install it by:

- Download sandstorm-0.tar.xz from the Checks tab on this pr.
- edit your /opt/sandstorm/sandstorm.conf, setting `UPDATE_CHANNEL=none`
- run `sandstorm update sandstorm-0.tar.xz`.

It can of course wait until morning, no rush. Sleep well.

**Comment by zenhack** [comment]
Ack, forgot we only do `make fast` in CI. Ok, when the new build finishes the artifact will be called `sandstorm-0-fast.tar.xz`.

**Comment by Phaen** [comment]
Works like a charm!

```
ACME.js notification: certificate_order {
  account: {
    key: { kid: 'https://acme-v02.api.letsencrypt.org/acme/acct/<ID>' }
  },
  subject: '*.<DOMAIN>',
  altnames: [ '*.<DOMAIN>' ],
  challengeTypes: [ 'dns-01' ]
}
ACME.js notification: challenge_select {
  altname: '*.<DOMAIN>',
  type: 'dns-01',
  dnsHost: '_acme-challenge.<DOMAIN>',
  keyAuthorization: '<KEY>'
}
ACME.js notification: _challenge_select {
  altname: '*.<DOMAIN>',
  type: 'dns-01',
  challenge: {
    identifier: { type: 'dns', value: '<DOMAIN>' },
    status: 'pending',
    expires: '2020-07-03T09:46:20Z',
    challenges: [ [Object] ],
    wildcard: true,
    type: 'dns-01',
    url: 'https://acme-v02.api.letsencrypt.org/acme/chall-v3/<CHALL>',
    token: '<TOKEN>',
    hostname: '<DOMAIN>',
    altname: '*.<DOMAIN>',
    thumbprint: '<THUMB>',
    keyAuthorization: '<KEY>',
    dnsHost: '_acme-challenge.<DOMAIN>',
    dnsAuthorization: '<KEY>',
    keyAuthorizationDigest: '<DIGEST}',
    dnsZone: '<DOMAIN>',
    dnsPrefix: '_acme-challenge'
  }
}
ACME.js notification: challenge_status { status: 'pending', type: 'dns-01', altname: '*.<DOMAIN>' }
ACME.js notification: challenge_status { status: 'valid', type: 'dns-01', altname: '*.<DOMAIN>' }
ACME.js notification: certificate_status { subject: '*.<DOMAIN>', status: 'valid' }
Certificate was successfully renewed!
Planning to renew certificate at: 2020-08-25T08:46:39.000Z
sandstorm/gateway.c++:935: info: Loading TLS key into Gateway
```

**Comment by kentonv** [comment]
Nice!

**Pull request merged**
