### PR TITLE
install.sh: Say we want "example" instead of "example.sandcats.io"

### PR DESCRIPTION
**Pull request by paulproteus**
See also #1506

### CODE REVIEW

**Comment by paulproteus** [comment]
I've run most of the `installer-tests` locally and am going to merge this now. Thanks to @elimisteve for noticing the UX deficiency and very helpfully submitting a pull request.

**Comment by paulproteus** [comment]
Self-merging because 100% docs

**Comment by elimisteve** [comment]
+1 thanks!

**Comment by kentonv** [comment]
> Self-merging because 100% docs

You mean 100% installer. :)

**Comment by paulproteus** [comment]
D'oh.

Thanks for reviewing my review! : D

**Pull request merged**
