### PR TITLE
Display an error message on catching ServiceConfiguation.ConfigError.

### PR DESCRIPTION
**Pull request by dwrensha**
This addresses https://github.com/sandstorm-io/sandstorm/issues/1355

### CODE REVIEW

**Comment by paulproteus** [comment]
FWIW I'm working on a patch that adds a simplistic UI to tell the administrator what to do. So I gently propose you wait for me to finish that and see if it supercedes this.

Sorry to not mention I was going to do that earlier this morning.

**Comment by paulproteus** [comment]
Suggested string change:

from:

- The Google login service has a configuration problem (Service not configured). Please contact your server administrator.

to: 

- Configuration problem: Service not configured. Please visit the Admin Settings page within Sandstorm, or ask your administrator to do so. To learn more, click Troubleshooting below.

**Comment by paulproteus** [comment]
Rationale: This makes sure the admin knows what to do, not merely that some action is required.

**Comment by paulproteus** [comment]
Adjusted the above to say "You may need an admin token" since people will probably need that, and this process will be confusing.

**Comment by dwrensha** [comment]
Since we now have a more complete strategy (#1374) for addressing #1355, I should independently justify this patch.

  1. I can't think of a situation where redirecting to /admin/settings is better than just reporting the error.
  2. The `var serviceName = instance.data.data.displayName;` line fixes a dereference of an otherwise-undefined variable.

**Comment by paulproteus** [comment]
+1 on those grounds

**Comment by kentonv** [comment]
I agree that this change is still needed: changing BASE_URL isn't the only way to end up in this situation. At least one user who reported this problem got there by deleting his Google account to which the OAuth credentials were attached.

I also agree with @paulproteus's wording change. In most cases the user reading the message will actually be the admin (of a personal server), so we should tell them what to do.

**Comment by dwrensha** [comment]
OK, I've updated to Asheesh's wording.

**Pull request merged**
