### PR TITLE
Support default role in the shell.

### PR DESCRIPTION
**Pull request by mquandalle**

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by kentonv** [comment]
Hmm I think line 254 should be updated as well (the API tokens dialog).

**Comment by kentonv** [comment]
Actually, no, scratch that. API tokens should probably have all the creator's permissions by default, since they're not for sharing but for connecting apps.

**Comment by kentonv** [comment]
Garply, ok to test.

**Comment by kentonv** [comment]
Apparently Meteor doesn't like this.

https://build.sandstorm.io/job/Sandstorm%20PRs/330/console

    Errors prevented bundling:
    While building the application:
    client/shell.html:312: Reactive HTML attributes must either have a constant
    name or consist of a single {{helper}} providing a dictionary of names and
    values.  A template tag of type BLOCKOPEN is not allowed here.
    ...                     {{#if obsolete}}styl...

**Comment by mquandalle** [comment]
Thanks Garply, this is fixed (this syntax used to work in Meteor <0.8 :-))

**Pull request merged**
