### PR TITLE
Prevent demo users from sharing by email. Increment dailySentMailCount when sharing by email.

### LINKED ISSUE #1906: Disable e-mail sharing for demo users and rate-limit for everyone else
It looks like someone has discovered that they can send spam messages through the Sandstorm sharing dialog. :(

We should:
* Disallow demo users from sending sharing e-mail. They'll need to share by link only.
* Rate-limit sharing emails sent by real users, probably using the same mechanism as we use to rate-limit email from apps.

This is somewhat of an emergency as the longer this spammer continues their activity the more reputation we lose.

### PR DESCRIPTION
**Pull request by dwrensha**
Closes #1906.

demo user

### CODE REVIEW

**Comment by neynah** [comment]
I would probably display it as help/detail text rather than having it in a box and change it to something simpler like:

"Sharing emails cannot be sent while in demo mode. Create an account to send sharing emails, or get a shareable link instead."

I don't think mentioning spam enhances the demo-users experience.

**Comment by dwrensha** [comment]
@neynah more like this?

simpler

**Comment by neynah** [comment]
Can you match the bottom padding of that text with the top padding? Otherwise, +1! :)

**Comment by kentonv** [comment]
Hmm, but I like having the UI shown (but disabled) so that people can see what they would be getting with a full account.

How about:
* Place the text in a red box (styled like the error messages in the admin UI).
* Show the regular sharing UI -- but with all inputs disabled -- under the error message.

**Comment by neynah** [comment]
Just talked to Kenton in person & I agree that his suggestion is an improvement. :+1:

**Comment by dwrensha** [comment]
I pushed a commit that looks like:
red box

**Comment by kentonv** [comment]
Hmm, almost there, but should the input boxes be gray or something so that they look more "disabled"?

**Comment by dwrensha** [comment]
pushed: grayed

**Comment by kentonv** [comment]
Great!

**Comment by ocdtrekkie** [comment]
Should the "get shareable link" tab be the default one when you expand this tab, if sharing by email is disabled? So the currently available sharing feature is most visible to the user when they're testing out Sandstorm?

**Comment by kentonv** [comment]
@ocdtrekkie has a good point.

I'm planning to push a hotfix later tonight. If a change to the default tab (for demo users) arrives before that I'll include it, otherwise it'll be in the next regular weekly release.

**Pull request merged**
