### PR TITLE
Deduplicate offered UiView capabilities.

### PR DESCRIPTION
**Pull request by dwrensha**
Immediately after saving, and before returning the cap to the user, check to see if we actually needed to this new cap. If not, then remove it.

### CODE REVIEW

**Comment by zarvox** [comment]
Ahh, I see.  This deletes the newly-generated ApiToken shortly after creating it, if it's the shell save()-ing the UiView, since the shell doesn't need the sturdyref to open a session.  This approach will only work for owner.user tokens, though, so we'll have to come up with something else if we want to support #2190 and also dedupe the tokens produced by the offer() to anonymous sessions.

I guess even with this patch, there'll be a brief window where the dupe `ApiToken` could be created and published but hasn't yet been deleted that the shell would still need to handle?

**Comment by dwrensha** [comment]
>there'll be a brief window where the dupe ApiToken could be created and published but hasn't yet been deleted that the shell would still need to handle?

What special handling might be needed? If there's a dupe, clients will already be deduping.

**Comment by zarvox** [comment]
> What special handling might be needed? If there's a dupe, clients will already be deduping.

No additional handling, but we don't get to drop the client-side deduping code as a result of this change.

**Comment by kentonv** [comment]
I wonder if save() itself should do this deduplification when it sees `sealFor = (user = (...))`. I guess it's not clear what it would return in that case.

Regarding anonymous users, it would be nice not to generate a new sharing link for every click. One possibility here is that the inner grain's webkey could be deterministically generated based on a hash of the webkey that the user is using to view the collection together with the collection grain's SturdyRef to the inner grain.

**Comment by dwrensha** [comment]
> I wonder if save() itself should do this deduplification when it sees sealFor = (user = (...)). I guess it's not clear what it would return in that case.

Maybe we could adjust `SystemPersistent` like so:

```capnp
interface SystemPersistent extends(Persistent(SystemObjectId, ApiTokenOwner)) {
  // ...
}

struct SystemObjectId {
  union {
    token @0 :Data;
    # New token.

    redundant @1 :Text;
   # Hash of existing token that's "as good" as the capability requested to be saved.
  }
}
```

I've shied away from this approach because it seems like overkill.

**Comment by kentonv** [comment]
Let's go with this for now.

**Pull request merged**
