### PR TITLE
Fix a typo in a comment

### PR DESCRIPTION
**Pull request by mquandalle**

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by mquandalle** [comment]
Hey garply! Don't build it, this change is super dangerous ;-)

**Comment by paulproteus** [comment]
Garply, ok to test

**Comment by paulproteus** [comment]
@kentonv I'm going to to take the liberty of merging this typo fix.

@mquandalle thank you for contributing it!

**Pull request merged**
