### PR TITLE
Implement the plan described in #1374

### PR DESCRIPTION
**Pull request by dwrensha**
Disables oauth services on BASE_URL change, but does not delete the config. Displays red boxes in the admin area, explaining why the services were disabled.

Looks like this:
admin

### CODE REVIEW

**Comment by paulproteus** [comment]
A question, fwiw: will this "fix" (actively go ahead and disable)
misconfigured Sandstorm installs, where someone changed BASE_URL and it
half-disabled their Google auth?

I'd prefer to see a change where it does actively fully disable someone's
Google auth, rather than keep it half-enabled as it is now. Which is to say
I'm hoping that an auto-update causes the Google login button to go away
from https://xamar.sandcats.io/ and https://rose.sandcats.io/ to force
those admins to look into why logging in isn't working.

That doesn't have to prevent this from merging, but fwiw, that's a thing I
want.

**Comment by kentonv** [comment]
I like it.

We should probably tweak the language to make clear that the user will need to modify the configuration at the Google or Github side. Probably we should explicitly tell them "You will need to update the OAuth redirect URL in the {Google Deveolper Console,Github application settings}".

I think that shoving a description string into the database probably isn't the right approach, especially when you consider localization (which we should do someday). Instead, we should define a specific set of reason IDs, or maybe the field should simply be `resetDueToBaseUrlChange` and we can add other flags later.

Please be sure to update the docs in db.js for the schema change.

@paulproteus People who modify BASE_URL after this change will have the "google" and "github" buttons disappear from the login drop-down, yes. I suppose we could retroactively "fix" existing servers using a migration that checks for the situation where the setting is enabled but the configuration is gone.

**Comment by dwrensha** [comment]
OK. Updated to not store the description string in the database. Also, now clicking on the checkbox after an automatic reset will pop up the configuration form.

**Comment by paulproteus** [comment]
: D​

**Pull request merged**
