### PR TITLE
`meteor add typescript`

### PR DESCRIPTION
**Pull request by zenhack**
First step towards starting to use typescript. This adds the meteor package, which causes the meteor build system to compile `.ts` and `.tsx` extensions to javascript. I also renamed a couple trivial files to make sure doing so doesn't break anything.

From here we can convert old code at our leisure, and write new code in typescript where convenient.

### CODE REVIEW

**Comment by zenhack** [comment]
Huh, build is failing. I'll investigate further.

**Comment by ocdtrekkie** [comment]
Is this working then at this point?

**Comment by zenhack** [comment]
Yeah, the last commit I pushed fixed the build. This is good to go.

**Comment by kentonv** [comment]
yay!

**Pull request merged**
