### PR TITLE
Remove / from BASE_URL for a CORS header

### LINKED ISSUE #1599: If BASE_URL ends in /, then /admin/settings shows a spurious WILDCARD_HOST warning
Steps to reproduce:

- Visit (e.g.) https://rose.sandcats.io/admin/settings and see that there is no big red warning text

- Edit `sandstorm.conf` so `BASE_URL=...` now _gains_ a `/` at the end of it

- Restart Sandstorm

Expected behavior:

- There is no big red warning text

Actual behavior:

- Big red warning text about WILDCARD_HOST

red-warning

### PR DESCRIPTION
**Pull request by paulproteus**
Close #1599

### CODE REVIEW

**Comment by paulproteus** [comment]
As a side note:

If I had followed @kentonv's advice to make this allowed to be accessed from all origins (`*`) then this bug would never have happened. But I do like the fail-closed nature of the way I wrote it! Hmm!

**Comment by paulproteus** [comment]
Testing done:

- Set rose.sandcats.io's BASE_URL to end in a `/`

- Reproduce the bug

- Install this code (built via `make fast`)

- Reload `/admin/settings`

- Notice the problem has gone away

- Adjust `WILDCARD_HOST` to be `*.zrose.sandcats.io`

- Reload `/admin/settings`

- Notice that I (correctly) see a big red warning.

- Fix the problem.

- Reload `/admin/settings`

- See the red warning go away.

**Comment by paulproteus** [comment]
<3 style checker

**Comment by kentonv** [comment]
I kind of suspect there are a lot more bugs that will happen if the root URL ends in a '/', so we should consider canonicalizing it at the source (in run-bundle).

**Comment by paulproteus** [comment]
+1 to that. I can see about doing that in the fullness of time. I filed a
bug.

**Pull request merged**
