### PR TITLE
Update zh-CN language file

### PR DESCRIPTION
**Pull request by misaka00251**
Still WIP, but most was translated.

Goal:
 - [x] Update to the latest version
 - [x] Fix zh-TW to zh-CN
 - [ ] Complete

### CODE REVIEW

**Comment by misaka00251** [comment]
Well, I will update rest of it in my spare time.

**Comment by ocdtrekkie** [comment]
Thanks! I'm always excited to see updated translation work!

I am a little confused by the "Fix zh-TW to zh-CN" commit description. Can you explain what this means?

**Comment by misaka00251** [comment]
Ok!
I see the commit history and all these years some contributors from Taiwan helped translate this project into Simplified Chinese (zh-CN) & Traditional Chinese (zh-TW). Those two can be converted by some program (or by hand :D), and I think they didn't finish the convert because they left some Traditional Chinese characters in the Simplified Chinese file.

**Comment by ocdtrekkie** [comment]
That makes sense, thanks for correcting our zh-CN!

**Comment by jadeqwang** [comment]
Hey, looks pretty good! Just one little typo fix needed on this line ("Sandstrom" -> "Sandstorm"):

"canUpgrade": "感谢您试用 Sandstorm 演示版！您的演示帐号已过期。如果您想继续使用 Sandstrom 并且让您的数据被永久保留，请登录。",

**Comment by kentonv** [comment]
I'll take care of the typo. Thanks for working on this!

**Comment by misaka00251** [comment]
Ah, my bad. I manually typed every "Sandstorm" and didn't recheck it. 🤣

**Pull request merged**
