### PR TITLE
Silence a bunch of unused-argument warnings

### PR DESCRIPTION
**Pull request by zenhack**
A migration is just a function that takes a SandstormDb and a backend,
but the majority of these functions don't actually use the backend.

This patch updates our eslint config to allow silencing an unused
argument warning by prefixing the argument with an underscore, then uses
this throughout migrations.js. This way we can start cutting down on
the noise.

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
It looks like this failed out on linting as 812 problems, despite you setting the threshold to 813...

**Comment by zenhack** [comment]
Should be fixed now.

**Comment by ocdtrekkie** [comment]
Is it difficult to make that only fail when the number of problems is *higher* than the threshold? It seems weird that if someone was to fix some linting issues, the check would fail, if they also didn't know to adjust that number.

**Comment by zenhack** [comment]
Quoting Jacob Weisz (2020-05-28 16:41:47)

>    Is it difficult to make that only fail when the number of problems is
>    higher than the threshold? It seems weird that if someone was to fix
>    some linting issues, the check would fail, if they also didn't know to
>    adjust that number.

See the comment right above that check; it would be easy to make it pass
if it's lower than expected, but the point is to make sure we don't
regress, so when we make improvements we should update the threshold so
that the improvements "stick."

**Comment by zarvox** [comment]
LGTM, thanks!

**Pull request merged**
