### PR TITLE
Changed text for Powerbox webkey

### PR DESCRIPTION
**Pull request by neynah**

### CODE REVIEW

**Comment by paulproteus** [comment]
Garply, retest this please

**Comment by paulproteus** [comment]
@jparyani requesting your review, since I am guessing you wrote these lines of code. I worked with @neynah on this earlier today and would love to see this land soon.

**Comment by jparyani** [comment]
Looks good to me.

**Comment by paulproteus** [comment]
:tada: for @neynah

**Comment by neynah** [comment]
& many more to come! :smirk:

**Comment by kentonv** [comment]
@paulproteus @jparyani Just to be clear, technically I'm supposed to be the one clicking "merge" for changes to the Sandstorm implementation. In this case it totally doesn't matter, just wanted to make sure the policy is clear. I added a more explicit ownership list here:

https://github.com/sandstorm-io/sandstorm/wiki/Pull-Request---Code-Review-Procedure

**Pull request merged**
