### PR TITLE
GitHub build workflow: don't build twice on prs.

### PR DESCRIPTION
**Pull request by zenhack**
Only build on prs and pushes to *master*, not arbitrary branches.

(I haven't actually tested this; we'll see what happens when I open the PR).

### CODE REVIEW

**Comment by zenhack** [comment]
Hm, doesn't seem to be triggering the build at all. will investigate.

**Comment by ocdtrekkie** [comment]
I guess the thing I thought about that concerns me with this approach is that when you push new commits to an open PR it won't run again automatically?

**Comment by zenhack** [comment]
Hm. What if we *just* did it on push, not PR?

**Comment by zenhack** [comment]
(Trying it)

**Comment by zenhack** [comment]
Ah, I misunderstood the behavior: it only duplicates the run when you push to another branch on the sandstorm-io repo (and thus is not triggering for my new push since the branch is on my repo).

Maybe the solution is for you guys to just send prs from your own forks, rather than using branches on the main repo?

**Comment by zenhack** [comment]
(actually, the reason it didn't run is because of an error in the config file; let's see how it behaves if I remove that).

**Comment by zenhack** [comment]
Actions do seem to run, but they aren't showing up here as checks:

https://github.com/zenhack/sandstorm/actions/

I think I'm going to close this.

**Pull request closed without merging**
