### PR TITLE
Make SVGs in about page work in Edge by using the background-image trick for SVGs

### PR DESCRIPTION
**Pull request by zarvox**

### CODE REVIEW

**Comment by zarvox** [comment]
@kentonv you may have already done something like this in your about-page restyling; feel free to close this PR and subsume it into your own if you prefer

**Comment by kentonv** [comment]
New about page looks good in IE, so closing this.

**Comment by zarvox** [comment]
Note that the old page was fine in IE up to 11; it only broke in Edge.

**Comment by ocdtrekkie** [comment]
Namely the issue in question is that the Uniregistry logo was like 24 x 24 pixels.

**Comment by ocdtrekkie** [comment]
Can confirm same issue on new about page in Edge.

uniregistry

**Comment by kentonv** [comment]
Ugghhhh, ok fine, fixed in af1fc6a.

**Comment by kentonv** [comment]
@ocdtrekkie can you confirm this is fixed on testrock now?

**Comment by ocdtrekkie** [comment]
It's fixed.

**Pull request closed without merging**
