### PR TITLE
re-enable Origin-based CSRF protection, whitelisting Gogs

### PR DESCRIPTION
**Pull request by dwrensha**
@kentonv mentioned that there were some apps other than Gogs that were apparently triggering the warning message, so those should be investigated before merging this.

The whitelist should probably also include older versions of Gogs, but I was unable to find them.

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
I can get you a full list of package IDs for any app when I get home in a few hours.

**Comment by kentonv** [comment]
lol, thanks @ocdtrekkie, but we actually do have these records. :)

**Comment by zenhack** [comment]
This logic has moved to the gateway; proxy.js no longer exists. The comments in the current version suggest that "The affected apps appear to be limited to Etherpad and Gogs." Are we confident enough in that assessment to merge an equivalent patch for the current implementation?

**Comment by kentonv** [comment]
@zenhack Well, it's possible that browser behavior has changed over the years... We may have to re-analyze this.

Actually, at this point it may make more sense to use the new `SameSite=strict` cookie flag on UI session cookies. That would protect against CSRF attacks from separate domains, though I suppose a CSRF is still possible from an app hosted on the same sandstorm server?

**Comment by zenhack** [comment]
Yeah, from what I can tell samesite=strict would treat everything under the sandstorm's wildcard domain as the same site.

**Comment by zenhack** [comment]
Just checked, can confirm that chrome still behaves as described in the comment (as does Firefox now; looks like the issue linked in the comment finally got addressed).

So a version of this change would still make sense (probably _in addition to_ samesite=strict). But probably we should close this and open a separate issue for that, since this is a patch to the old js version of the code that doesn't exist anymore.

**Comment by zenhack** [comment]
I opened #3358 for the issue this is trying to address (and #3357 for the samesite=strict idea). We can close this.

**Pull request closed without merging**
