### PR TITLE
Apply `jscs --fix shell` and fix up non-auto-fixed things under shared/

### PR DESCRIPTION
**Pull request by zarvox**
There's a long tail of packages that need to be fixed up, but this gets the rest of the non-package code into compliance.

### CODE REVIEW

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by kentonv** [comment]
Single-quoted strings? :(

**Comment by jparyani** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
I'm going to abandon this PR for now, since 1) it prefers single-quoted strings, which we agreed to abandon and 2) it no longer rebases cleanly.

I will have a new one up shortly.

**Pull request closed without merging**
