### PR TITLE
Avoid showing "Restore grain backup" on app install page

### LINKED ISSUE #1403: App install confirmation page should not show "Restore grain backup..." button
Since you don't have the app installed yet, you won't be able to restore a grain using that package, and install time is not the right time to encourage a user to do this anyway.

pixels1

@paulproteus can I assign this one to you, since you were the one who added this button?

### PR DESCRIPTION
**Pull request by paulproteus**
Close #1403

Thanks @zarvox for noticing.

### CODE REVIEW

**Comment by paulproteus** [comment]
To see the "before" screenshot of the install page, view issue #1403 

Install page after this change:

install-page

App details page after this change (note the "restore grain backup" UI is present still)

app-details-page

**Comment by ocdtrekkie** [comment]
Random sadness: The GPG key going off the side of that screenshot.

**Comment by paulproteus** [comment]
Agreed @ocdtrekkie

**Comment by paulproteus** [comment]
Ready for your review/merge @kentonv

**Comment by zarvox** [comment]
Yeah.  Maybe I'll try flexboxing the fingerprint on blur day so it'll wrap the first and second half neatly.

@paulproteus thanks for looking into this :)

**Pull request merged**
