### PR TITLE
Rework the way updates work to fix #3584

### LINKED ISSUE #3584: Permissions error causing test failures
I finally spent a bit of time debugging the batch of new (~19) test failures we started seeing a month or two ago. For reference, I've attached a full log from `make test TESTCASE=tests/backup-restore.js`, which is one of the relevant tests; the many of the other tests fail with the same error.

The interesting bit is this, error, which comes when setting up the sandbox for grains during test:

```
kj/io.c++:365: failed: miniposix::write(fd, pos, size): Operation not permitted; fd = 3
```

The stack trace pointed to this call:

https://github.com/sandstorm-io/sandstorm/blob/0d53a6646ab99c2cd4e54d2fc2d04d69f1e18366/src/sandstorm/supervisor.c%2B%2B#L936

The error results in grains failing to start, and therefore causing the overall test to fail. I haven't ever seen this happen on an actual install (even a dev one), only when running the test suite.

I suspect something changed in the kernel that is affecting this (nothing changed on our end), but I don't really understand why this fails, or exactly what the relevant difference is between test & prod.

I would be interested to hear from folks wrt:

- Whether you can reproduce the error on your system.
- What distro & kernel version you're running.

Probably the next step is to see if we can an find a system that still works, and see if we can get it to fail on a newer kernel, and if so bisect.

[t1.log](https://github.com/sandstorm-io/sandstorm/files/7535005/t1.log)

### PR DESCRIPTION
**Pull request by zenhack**
Rather than having the update monitor itself exec the newly downloaded
version of sandstorm, it simply exits (with status 0), and its parent
process takes this as an indictation that it should re-spawn it (with
the new version). This avoids the need to map ourselves to UID 0 in the
user namespace, which avoids the EPERM error we were getting when
later hiding the real UID from a grain.

Per discussion on the issue, the old design no longer works as of Linux
5.12, after which spawning the grain we would need CAP_SETFCAP, which we
do not want to have.

---

This seems to basically work, but I'm marking it as a draft for now for a couple reasons:

- [x] It touches the update monitor, so I want to test it very thoroughly before merging; an update that broke updates would be very bad.
- [x] There are still *some* test failures, and while I expected that (there were known failures before we started having this problem) I want to stare at them a bit to make sure I understand what's going on.
- [x] There is a minor issue where when stopping sandstorm, a message is spuriously printed stating that sandstorm exited abnormally, even when it did not. Doesn't really cause problems, but I should fix it.

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
These (found in your Action results) existed prior to the large number of account failures, so I think we are good there, at least in getting back to where we used to be.

 ✖ tests/account #3239 
 ✖ apps/web-publishing #3240 

You can see there are two other tests which also fail intermittently, all tracked here: https://github.com/sandstorm-io/sandstorm/milestone/19

**Comment by zenhack** [comment]
Ok, yeah, it looks like we're good then. I was still seeing the appHooks failure locally and I couldn't remember if that one was one of the existing ones.

**Comment by zenhack** [comment]
Might make sense to add this/#3584 to that milestone.

**Comment by ocdtrekkie** [comment]
Done.

**Comment by zenhack** [comment]
I can't seem to reproduce the error on stop anymore; maybe I fixed it and forgot, or maybe I was running a stale version when I last tested. In any case, it appears to work.

I still want to do a bit more testing; I patched the URLs used for updates and checked a bunch of stuff manually, both for a system wide install and just running the test configuration as an unprivileged user:

- The manual `sandstorm update` command works as expected.
- We still check for and download updates 10m after startup
- We check for an update after an hour if a previous check fails.

I still want to check:

- [ ] A valid, correctly signed update goes all the way through.
- [ ] Afterwards, update checks happen after 24 hours.

I'll need to futz around with the signing code to check this, and then it's mostly a matter of backgrounding it and checking back.

I'm being way more careful about this patch than I normally would be; I'm pretty confident it's fine, but breaking automatic updates would be very very bad, so I'm being really pedantic about this.

At some point I'd like to have some actual automated tests for this stuff, but that will have to wait.

**Comment by zenhack** [comment]
Alright, finished with the above checks and everything seems to work; marking read for review.

**Comment by zenhack** [comment]
(2) does seem much simpler. Implemented in #3609, closing.

**Pull request closed without merging**
