### PR TITLE
Fix SMTP listening in run-dev mode.

### PR DESCRIPTION
**Pull request by dwrensha**
Fixes https://github.com/sandstorm-io/sandstorm/issues/1916.

### CODE REVIEW

**Comment by dwrensha** [comment]
In run-dev mode, [meteor-bundle-main.js](https://github.com/sandstorm-io/sandstorm/blob/80e91c59f8d7b62e8700a4bcef9306a31026427c/meteor-bundle-main.js) does not get run at all.

**Comment by paulproteus** [comment]
One problem is that this will crash if SMTP_LISTEN_PORT=25, right? But maybe that is just life.

**Comment by paulproteus** [comment]
I'll manually test my guess now, one sec.

**Comment by paulproteus** [comment]
In manual testing with this patch:

- With `SMTP_LISTEN_PORT=25` in sandstorm.conf: `run-dev.sh` now starts up OK, but doesn't listen on port 25. I can live with that.

- With `SMTP_LISTEN_PORT=30025` in sandstorm.conf: `run-dev.sh` now starts up OK and does in fact listen on port 30025.

So I'm +1 on this PR. Thanks @dwrensha for writing it.

Non-showstopper feedback:

- It would be nice run-dev.sh were to open the port and pass it in, as an fd, so that the code wouldn't have to be aware of `run-dev.sh`. But I don't think that's crucial.

**Comment by kentonv** [comment]
Turns out this was also necessary for blackrock, btw!

**Pull request merged**
