### PR TITLE
Update email-from-apps.md

### PR DESCRIPTION
**Pull request by kirjur**
Fix frond email.capnp link.

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by paulproteus** [comment]
Hi @kirjur ! Thanks for this docs fix. I'm grateful to you for noticing it and taking the time to submit a pull request with the fixed link. I'm doubly grateful since I believe I am the person who added the bad link in the first place.

I'll merge this right now, and do a docs push.

**Comment by paulproteus** [comment]
Done. You can see the fixed link here: https://docs.sandstorm.io/en/latest/developing/email-from-apps/

Thanks again!

**Comment by kirjur** [comment]
Hi @paulproteus ! Thanks for feedback, this is my first commit on a open source project:)

**Comment by paulproteus** [comment]
That's so cool! In a past life, I spent a lot of time welcoming people to
open source projects. So let me be sure to welcome you, kirjur.

I'd love to get to know you a little more -- feel free to reply to
asheesh@sandstorm.io (my email address) rather than here on GitHub:

* What do you find appealing about Sandstorm?

* What is one thing you already know, tech-wise, or design-wise? Not
necessarily related to Sandstorm, just trying to learn more about you.

* What do you want to know more about with regard to Sandstorm, or what can
I help you do with Sandstorm?

​
Thanks so much for saying so and welcome to the open source club!

**Pull request merged**
