### PR TITLE
Clarify that dev install can be used for Sandstorm dev

### PR DESCRIPTION
**Pull request by paulproteus**
Hopefully this addresses the concern that resulted in #1652

### CODE REVIEW

**Comment by paulproteus** [comment]
I'll probably have to update installer-tests; will do that in a commit on top. Curious for @dwrensha 's +1 -1 on this text.

**Comment by dwrensha** [comment]
+1

I like "typical install" better than "full install".

It is a bit awkward to use the word "development" twice in option 2, but I can't think of any improvements that also keep the "localhost-based" bit.

**Comment by kentonv** [comment]
Is the word "live" a possible alternative to "production"? "A live server"...

Just an idea, but I leave it to @paulproteus to decide.

**Comment by paulproteus** [comment]
FWIW, I'm -0.5 on "live". I don't know that it adds any information beyond
"typical".

I'll land this tomorrow, after double-checking with installer-tests.

**Comment by paulproteus** [comment]
Self-merging because 100% install.sh and installer-tests.

The installer-tests pass on my laptop.

**Pull request merged**
