### PR TITLE
Add a missing `.defaultText`.

### PR DESCRIPTION
**Pull request by dwrensha**

### CODE REVIEW

**Comment by dwrensha** [comment]
This is broken. Do not merge yet.

**Comment by dwrensha** [comment]
The problem is that `action` can be one of two things:
  1. an entry in the `UserActions` actions table, in which case `action.nounPhrase` is a string.
  2. a JSON-encoded Manifest.Action, in which case 'action.nounPhrase` is a `Util.LocalizedText`.

**Comment by zarvox** [comment]
Hmmm, the entry in the `UserActions` table should probably also be a `Util.LocalizedText`.  Are we dereferencing it too soon when we insert it into the UserActions table?

**Comment by kentonv** [comment]
Yes, probably we shouldn't be dereferencing this in the first place. Not sure whether it would be better to do a migration to fix this or simply check `typeof` and handle both cases.

**Comment by kentonv** [comment]
Closing so that I don't accidentally merge. Please re-open when ready, or file an issue to track the bug.

**Pull request closed without merging**
