### PR TITLE
Adjust Vagrantfile to do file sharing via NFS

### PR DESCRIPTION
**Pull request by paulproteus**
The purpose of this change is to stop using the VirtualBox-native
file sharing system, which seems to be both slower and less POSIX-y
than NFS.

### CODE REVIEW

**Comment by paulproteus** [comment]
I believe this may fix the build problems in #263 (though this commit doesn't change the Vagrantfile to actually do the build). @diracdeltas if you want to test that, I recommend doing:

```
$ vagrant up
$ vagrant ssh
$ sudo sudo apt-get install build-essential libcap-dev xz-utils zip \
    unzip imagemagick strace curl clang-3.4 clang nodejs
$ curl https://install.meteor.com/ | sh
```

and then seeing if it builds for you.

@awans I believe this will fix the issues you were having on Mac OS where Meteor/Mongo couldn't run properly. If you can test that, I'd greatly appreciate it.

I'll probably merge this once the tests pass, rather than wait on the above, since I believe it makes things no worse.

**Comment by paulproteus** [comment]
I'm adding a commit that has Vagrant use more RAM, and I'm also going to test right now that the `apt-get install` (etc.) lines above result in a successful build.

**Comment by paulproteus** [comment]
I've tested locally that this setup can compile Sandstorm, so I will ship it.

@awans if you can test on Mac OS sometime, that'd be stellar.

**Comment by kentonv** [comment]
BTW, if you want to reduce the parallelism of the build, you can set the `PARALLEL` make var, e.g.:

    make PARALLEL=2

The default is determined by invoking `nproc`.

**Comment by awans** [comment]
Hey @paulproteus, I ran into some trouble getting the provisioning script to run—seems like my sudoers privileges weren't getting created correctly?

I figure a short screencast is the easiest way of describing the behavior I see:

https://www.dropbox.com/s/627rnjgs50vmufd/vagrantfile.mov?dl=0

I'm probably missing something obvious :/

**Pull request merged**
