### PR TITLE
Bind to SMTP_LISTEN_PORT in C++-land (now ready for review/merge)

### PR DESCRIPTION
**Pull request by paulproteus**
Close: #1386 

Testing done so far:

- [x] Run this code on my laptop.
- [x] Verify that localhost:30025 is still routed to the Sandstorm SMTP server.
- [x] Verify that Sandstorm's HTTP service seems to work OK.

Testing still to do:

- [x] Run this on a real server somewhere and manually test that HTTPS and two alternate HTTP ports still work.

- [x] Manually test inbound email to a grain.

Notes to reviewers:

- I believe all this code works, so feel free to give me review feedback on the code right now, so I can get it merged faster.

### CODE REVIEW

**Comment by paulproteus** [comment]
Thanks @Garply for helping me find & fix my bad JS style!

**Comment by paulproteus** [comment]
I've done all the manual testing listed above, and it passes. @kentonv can I get your review/merge on this?

**Comment by kentonv** [comment]
Is the `SANDSTORM_SMTP_PORT` environment variable no longer used? Can we delete https://github.com/sandstorm-io/sandstorm/blob/bind-to-smtp-listen-port-from-runbundle/src/sandstorm/run-bundle.c++#L1921 ?

Is there a plat to support TLS, since presumably we'll no longer be telling people to run a proxy in front of this? Do we need to support the SMTPS port or will we strictly support STARTTLS?

**Comment by jparyani** [comment]
`SANDSTORM_SMTP_PORT` is used for testing purposes at the moment.

**Comment by kentonv** [comment]
AFAICT, this change removes all references to `SANDSTORM_SMTP_PORT` in the repository except for the `setenv()` line. @jparyani how is it used "for testing"?

**Comment by jparyani** [comment]
Hmm that's interesting. It looks like there's a typo in tests/run-local.sh that hilariously lines up with another typo in the tests themselves. Essentially we've been defaulting to port 30025 on both ends for a while now. This might explain the flakiness with the email tests...

**Comment by kentonv** [comment]
@jparyani Amazing! But even if the tests were setting the correct environment variable, `run-bundle.c++` overrides it with the value in the config file (or with 30025 if the config file doesn't specify). It was never possible to specify this in any way other than the config file, AFAICT.

**Comment by dwrensha** [comment]
@jparyani: what typo are you referring to? run-local.sh [does in fact write to a config file](https://github.com/sandstorm-io/sandstorm/blob/v0.159/tests/run-local.sh#L103-L124). I've observed that [tests/commands/sendEmail.js](https://github.com/sandstorm-io/sandstorm/blob/v0.159/tests/commands/sendEmail.js#L6) does see a generated non-default value for `SMTP_LISTEN_PORT`, and [tests/commands/assertReceiveEmail.js](https://github.com/sandstorm-io/sandstorm/blob/v0.159/tests/commands/assertReceiveEmail.js) does see a generated non-default value for `SMTP_OUTGOING_PORT`. The `EADDRINUSE` that we've been seeing happens in assertReceiveEmail.js, when `SMTP_OUTGOING_PORT` is in use.

**Comment by paulproteus** [comment]
I'll take a look at these questions after I finish something this morning.

**Comment by jparyani** [comment]
Sorry, this was confusion on my part, ignore my comment from before. We no longer need the environment variable, and should probably delete it as Kenton suggested. I got confused since we used to rename the environment variable in run-bundle.c++.

**Comment by kentonv** [comment]
@paulproteus If you agree the setenv() line can be removed, I'm happy to apply that change myself if it helps. Everything else looks good to me.

**Comment by paulproteus** [comment]
In this branch, we seem to use SMTP_LISTEN_PORT in a few places:

```
tests/commands/sendEmail.js:var SMTP_LISTEN_PORT = parseInt(process.env.SMTP_LISTEN_PORT, 10) || 30025;
tests/commands/sendEmail.js:var pool = simplesmtp.createClientPool(SMTP_LISTEN_PORT);
tests/run-local.sh:export SMTP_LISTEN_PORT=$(getNewPort)
tests/run-local.sh:SMTP_LISTEN_PORT=${SMTP_LISTEN_PORT}
```

-0 on merge for now, until I fix those lines.

**Comment by kentonv** [comment]
@paulproteus I think we've determined that those lines are not related. The setenv line is:

    KJ_SYSCALL(setenv("SANDSTORM_SMTP_PORT", kj::str(config.smtpListenPort).cStr(), true));

That is, it sets `SANDSTORM_SMTP_PORT`, not `SMTP_LISTEN_PORT`.

**Comment by paulproteus** [comment]
Thanks for that clarification, @kentonv ! I've pushed a commit that removes the environment variable and I'm happy (once it passes tests) to see it merged & released.

**Comment by paulproteus** [comment]
Note to self: Attempt to get this merged >= Tue Apr 26, 2016, so that Kenton can do an urgent Oasis hotfix during Mon Apr 25.

**Pull request merged**
