### PR TITLE
demo: Call ourselves a productivity suite

### PR DESCRIPTION
**Pull request by paulproteus**
See also: #2545

### CODE REVIEW

**Comment by paulproteus** [comment]
Screenshot of new (left) & old (right) demo page:

screenshot from 2016-09-13 17 28 12

Screenshot of new (left) & old (right) appdemo page:

screenshot from 2016-09-13 17 34 48

Requesting design/string sanity-check from @neynah before asking @kentonv to review/merge.

**Comment by paulproteus** [comment]
Assigning @neynah for her feedback; once she is +1 I will assign to @kentonv for review/merge.

**Comment by kentonv** [comment]
For appdemo, the wrapping to three lines disrupts the design. Can you give it a little more horizontal space so that it doesn't wrap like that?

**Comment by neynah** [comment]
> For appdemo, the wrapping to three lines disrupts the design. Can you give it a little more horizontal space so that it doesn't wrap like that?

Pretty much what I was going to write. +1

**Comment by paulproteus** [comment]
I guess I noticed that, but was hoping no one else would notice. I guess that's not a very good strategy. :) Fix forthcoming.

**Comment by paulproteus** [comment]
New screenshots:

Revised appdemo & demo:

screenshot from 2016-09-14 12 59 43

Before & after for appdemo:

screenshot from 2016-09-14 12 56 08

I do wonder if I should find a compromise width here that allows the demo text have >1 word on its second line.

**Comment by paulproteus** [comment]
I think I'm OK with this as-is. Curious for fresh +1/-1 from @neynah

**Comment by neynah** [comment]
+1!

**Comment by paulproteus** [comment]
@kentonv ready for your review/merge.

**Pull request merged**
