### PR TITLE
Rekey Gitweb package

### PR DESCRIPTION
**Pull request by abliss**
NB I have not yet tested this at all.

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
His username confuses this, but @dwrensha is David Renshaw. :)

**Comment by abliss** [comment]
Thanks, spelling fixed.

**Comment by abliss** [comment]
@dwrensha has responded to my PR, so let's hold off on rekeying for now.

**Comment by ocdtrekkie** [comment]
Closing for now

**Pull request closed without merging**
