### PR TITLE
Stop using RC4; pick basically-reasonable ciphers

### PR DESCRIPTION
**Pull request by paulproteus**
This gets us an A- on the Qualys labs checks. I will investigate further
later to get a higher score.

### CODE REVIEW

**Comment by paulproteus** [comment]
I'm going to manually test this on `rose.sandcats.io` now.

**Comment by zarvox** [comment]
Consider using https://wiki.mozilla.org/Security/Server_Side_TLS as your reference ciphersuite source.

**Comment by paulproteus** [comment]
Ya, I did that first, but then found that I still couldn't get PFS stuff to
work, so am using the oasis config for now, and will re-examine later.​

**Comment by paulproteus** [comment]
Of note, I am not sure how to integrate the need for `dhparam` with the nodejs `https.createServer()` API in node 0.10.x. I filed a bug to remind me to think more about that later, #941

**Comment by paulproteus** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=test6.rose.sandcats.io&hideResults=on is our `A-` report card, which I am happy enough with for now, and request review/merge from @kentonv .

Note that, as in all things in our little HTTPS world, this patch was slightly more complicated than I expected. We have to set this parameter not just for the default `createServer()` but also in the `SNICallback` or else we only use good certs for the `*.invalid` hostname. (-:

**Comment by paulproteus** [comment]
Garply, retest please

**Comment by kentonv** [comment]
This doesn't appear to match Oasis' config. Our cipher list is:

    ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;

I think it's important that we support PFS. ECDHE should work without the need for DH parameters. I am OK with not supporting DHE (which requires DH parameters to be secure); this means older browsers will not get PFS but new browsers will.

**Comment by paulproteus** [comment]
I must have found the wrong line to copy.

I will look into this in a bit, presumably today. If Jason's still possibly
interested, that would be way cool. I'll ping Jason before I dig into this,
but it won't be for a little while.

**Comment by kentonv** [comment]
I merged this, but I think I accidentally made it the subject of a rebase where I didn't change anything, but this caused the hash to change, so github doesn't recognize it as a merge. Oh well, it's merged. I also made a subsequent commit changing the cipher suite to actually match oasis, although this doesn't help as it turns out Node 0.10.x simply does not support DHE nor ECDHE. :( Meteor is stuck on node 0.10.x so we can't do anything about it for now.

Luckily our certs rotate every week?

**Pull request closed without merging**
