### PR TITLE
Tell the client about UserActions so it knows when not to create them

### LINKED ISSUE #221: "Try app" leads to lots of "actions"
Steps to reproduce:

* Visit https://demo.sandstorm.io/appdemo/70awyqss6jq2gkz7dwzsnvumzr07256pzdt3hda9acfuxwh6uh7h

* Click the button

* Repeat the above two steps 4 times

Result:

too-many-actions

Desired result:

Only one button at the top

### PR DESCRIPTION
**Pull request by paulproteus**
Close #221

### CODE REVIEW

**Comment by paulproteus** [comment]
Testing done:

* As a regular (non-demo) user, click on the "Try {{ appName }}" a few times. Notice that the number of "Create appName instance" buttons stays the same.

* Also tested as a demo user.

**Comment by kentonv** [comment]
Will probably push a release tomorrow.

**Comment by paulproteus** [comment]
Yippee. Thanks.

**Comment by kentonv** [comment]
Fix is live on demo.sandstorm.io (build 0.64).

**Pull request merged**
