### PR TITLE
Add deSEC DNS provider

### PR DESCRIPTION
**Pull request by rs22**
deSEC (https://desec.io/) is a non-profit organization offering a free DNS service that can be configured using a REST API (which, by the way, is also [open source](https://github.com/desec-io/desec-stack)).

In order to add support for them as a DNS provider in Sandstorm, I've created an [acme-dns-01-desec](https://www.npmjs.com/package/acme-dns-01-desec) npm package, to which this PR adds a reference.

An example options json looks like this:
```json
{
  "token": "<auth token>"
}
```
The deSEC docs describe how to obtain the token using their API: https://desec.readthedocs.io/en/latest/auth/tokens.html
There is no UI for that yet.

During development, I've added the npm package directly into this repository, so feel free to stash the commits.

### CODE REVIEW

**Review by ocdtrekkie — CHANGES_REQUESTED** [review]
DNS providers should be listed alphabetically. Also, I think ACMS.js plugins that aren't first party to ACME.js or included in the Sandstorm repo directly are credited in third party works used, so you probably should add this plugin there too.

**Comment by ocdtrekkie** [comment]
Awesome to see this (and cool to learn about this service). I left a couple notes, but I imagine this should be really easy to get in the next release.

**Comment by rs22** [comment]
Thanks for your feedback! I hope everything looks good now.

**Review by ocdtrekkie — APPROVED** [review]

**Comment by ocdtrekkie** [comment]
It looks good to me!

**Comment by kentonv** [comment]
This looks great. Thanks for moving it out into its own npm package -- that seems like the right thing to do. (The only reason sandcats is in-tree is because sandcats isn't designed to be used by anything other than Sandstorm...)

Also thanks for keeping the code short and dependency-free. :)

**Pull request merged**
