### PR TITLE
Update README to point to Packaging Guide

### PR DESCRIPTION
**Pull request by yuvipanda**

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by paulproteus** [comment]
Garply, ok to test

**Comment by paulproteus** [comment]
Note @yuvipanda that the even-better packaging guide is at https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial/ . Someone (probably me?) needs to finish migrating the docs from github wiki => docs.sandstorm.io. I just made docs.sandstorm.io a thing last Wednesday.

**Comment by kentonv** [comment]
I think @paulproteus integrated this into his README update submitted yesterday. Thanks!

**Pull request closed without merging**
