### PR TITLE
Vagrantfile: set cpus/memory on libvirt too

### PR DESCRIPTION
**Pull request by zarvox**

### CODE REVIEW

**Comment by paulproteus** [comment]
This looks good to me. I will wait to merge it until I test it. Along those
lines, it'd be cool if we had some kind of test suite for the Vagrantfile.

**Comment by paulproteus** [comment]
I just manually tested this and it seems OK. However, on principle, I refuse to merge pull requests while the build is red. So I'll wait for that to get fixed.

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by paulproteus** [comment]
Thanks @garply !

**Pull request merged**
