### PR TITLE
fixed the short text for the update console command

### PR DESCRIPTION
**Pull request by alandrees**
Simple text fix for the command line uninstall option.

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by dwrensha** [comment]
Thanks! This looks not quite right, though. Shouldn't you instead replace the *second* instance of "Generate admin token" ?

**Comment by dwrensha** [comment]
For consistency with the other commands, the replacement text should probably be in the imperative mood, like "Uninstall Sandstorm."

**Comment by alandrees** [comment]
@dwrensha ahhh yeah, good point.  I'll fix and create another PR.

**Pull request closed without merging**
