### PR TITLE
Get libsodium to build with the new include/sodium/private directory.

### PR DESCRIPTION
**Pull request by dwrensha**
This should fix the build once https://github.com/jedisct1/libsodium/commit/3927cad829156038a6baa9821d041b76b2f8f0f8 gets pushed to the libsodium stable branch.

### CODE REVIEW

**Comment by dwrensha** [comment]
(This should obsolete #1757)

**Comment by dwrensha** [comment]
Garply, retest this please.

**Comment by jedisct1** [comment]
All good?

**Comment by dwrensha** [comment]
@jedisct1: yep, this works.

**Pull request merged**
