### PR TITLE
Add facility for admin to take heap dumps for memory leak debugging.

### PR DESCRIPTION
**Pull request by kentonv**

### CODE REVIEW

**Comment by kentonv** [comment]
Merging now for release.

**Comment by zarvox** [comment]
Combined with #2154, LGTM

**Comment by zarvox** [comment]
Actually, it looks like `npm-shrinkwrap.json` needs to be regenerated whenever you add a package to `package.json`.  You can regenerate it with:

```bash
cd shell/
meteor npm shrinkwrap
```

**Comment by zarvox** [comment]
I tried doing what I said, and that led me to hit a bug in npm, so I worked around it in #2156.

**Pull request merged**
