### PR TITLE
Docs: Square up search box

### PR DESCRIPTION
**Pull request by ocdtrekkie**
Attempt 2, the first one did the search box on the full page search page, this one should do it for the sidebar: And it is pulled out into extra.css too which is nice.

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
Pictures in #3258

**Comment by zenhack** [comment]
Looks reasonable to me though I haven't built & verified it myself. Fine with merging if you've tested.

**Comment by ocdtrekkie** [comment]
This time I made sure I actually got the expected result from mkdocs serve after being burned before. :P

**Comment by ocdtrekkie** [comment]
Definitely actually works live too! \o/

**Pull request merged**
