### PR TITLE
Add account settings tests.

### PR DESCRIPTION
**Pull request by wdk122**

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by kentonv** [comment]
Hey, just wanted to mention, I saw this, and this is really cool! Nice work figuring out the test framework without even asking any questions. :) I plan to look closer this weekend.

For the account settings test, I think we should also test that the profile information is correctly passed on to apps. This will require using a test app, though, which raises a bunch of new questions. There's already a C++ test app in the repository that uses the raw API, but it may also make sense to create a new Node.js-based test app that uses sandstorm-http-bridge, to test both. We also have a variety of out-of-tree test apps which aren't very well organized currently, but we could also consider adopting one of those. Anyway, let's chat about this over the weekend.

**Comment by kentonv** [comment]
Garply, OK to test.

**Comment by wdk122** [comment]
I've created a new pull request at [#2939](https://github.com/sandstorm-io/sandstorm/pull/2939) to follow up.

**Pull request merged**
