### PR TITLE
Move "restore backup" to /grains page

### PR DESCRIPTION
**Pull request by paulproteus**
Also:

- Add a "Restore grain backup" button within each app.

- Move "Upload" to the top of the apps list, so that the
  main "Install" button is more visible.

- Show the "Search..." UI always on the /apps/ page, even if
  there are no apps. This improves consistency and gives us a
  place to put the "Upload" button.

- Add a border around the "Install" (from app market) button so
  that it is at least as visible as "Upload".

- Only focus the search text input if there are any apps to search.
  This way, when landing on /apps/ for the first time, one is not
  tempted to search.

### CODE REVIEW

**Comment by paulproteus** [comment]
Testing done:

-  Visited /apps and uploaded an app successfully using the new, shrunk upload button.

- Visited /grains and restored a backup successfully using the new "restore backup" button there.

- Visited an app page and restored a backup successfully using the new "restore backup" button there.

**Comment by paulproteus** [comment]
Relevant screenshots:

Smaller upload button

ew-003


Restore backup button on `/grains`

ew-558

Restore backup on app details

ew-761

**Comment by paulproteus** [comment]
@neynah curious for your +1 -1 on the buttons & placement & size etc.

**Comment by neynah** [comment]
Just some additional padding on the buttons

image

**Comment by paulproteus** [comment]
I've made changes that are now approved by @neynah .

@kentonv I'd love your review/merge!

**Pull request merged**
