### PR TITLE
docs: Explain why you should back up HTTPS certs during a server move

### LINKED ISSUE #2062: docs: Mention HTTPS certs are smart to xfer between machines in backups.md
Thanks @jacksingleton for bringing this to my attention.

### PR DESCRIPTION
**Pull request by paulproteus**
Close #2062

### CODE REVIEW

**Comment by paulproteus** [comment]
Hi @jacksingleton,

I humbly request your review on this docs change! Specifically, please answer the following question: When you were setting up a server a few months ago, and ran into a problem where your Ansible automation scripts triggered a weird error and Sandstorm couldn't start, would this docs change have saved you?

This patch changes this section:

- https://github.com/sandstorm-io/sandstorm/blob/docs-mention-move-sandcats-certs-issue2062/docs/administering/sandcats.md#manually-moving-sandcats-client-certificates-to-a-new-sandstorm-install

as well as **Diagnosing "Not Authorized" problems** right underneath it.

Awaiting your +1 or feedback, or a statement that you don't have time to review, @jacksingleton!

**Comment by paulproteus** [comment]
Hi @jacksingleton ! I'm going to merge this now so it's live in the docs, but I am still hopeful for your review!

**Comment by paulproteus** [comment]
Any feedback you have is very welcome.

**Comment by jacksingleton** [comment]
Oops I tried to reply to this by email on Friday but it didn't end up on Github for some reason...

This is great, the "Note that if you are using sandcats.io free HTTPS certificates, we suggest also backing up and restoring the contents of [https]..." paragraph is exactly what I needed.

+1 !

**Comment by paulproteus** [comment]
Yippee!

**Pull request merged**
