### PR TITLE
JSCS compliance for everything not in packages

### PR DESCRIPTION
**Pull request by zarvox**
This time, with double quotes preferred, more ES6 support, and a pile of rebased manual fixes.

### CODE REVIEW

**Comment by zarvox** [comment]
Test failures are reproducible locally, so I'll look into figuring out why.

**Comment by zarvox** [comment]
Okay, looks like it's unsafe to convert 

`var namedFunction = function () { ...`

into

`const namedFunction = function () { ...`

if namedFunction is declared within a block e.g. `if (Meteor.isClient) {` but then used outside of that block.  Which is something we shouldn't be doing at all, but which we definitely do in `shared/admin.js` and `shared/shell.js`.  I'll look for similar problems elsewhere.

**Comment by zarvox** [comment]
I audited the codebase for other potentially dangerous blocks by running

`ag '\ +const.*= function'`

and

`ag '^\ +const.*=.*(.*) => {'`

and checking the output.

Any remaining blocks that match those patterns, I manually verified are safe to leave as-is, currently.

**Comment by paulproteus** [comment]
yay!

**Pull request merged**
