### PR TITLE
Add developer portal

### LINKED ISSUE #1881: Rename "Developing" in docs to "Developer portal"
@jadeqwang and @neynah and I are interested in clarifying to website visitors that the Sandstorm developer docs are the best place to start when people want to find technical information about developing apps for Sandstorm. Given that, here are some next steps:

### Sandstorm repo

- Sandstorm GitHub README: Make it crisper; refer to developer portal

- Adjust /developing/ to have a few icons at the top to other places. Mockup:

screenshot from 2016-04-18 13_48_47

### sandstorm-website repo

- See https://github.com/sandstorm-io/sandstorm-website/issues/173

### PR DESCRIPTION
**Pull request by paulproteus**
Close #1881

More specifically:

- Change mention of app developer tutorial in README to instead
  link to developer portal.

- Add a flexbox grid at the top of /developing/ for quick access
  icons to next steps, to make it feel more like a "developer
  portal" (cc: @jadeqwang), supported by `docs/extra.css`

While I was at it:

- Move the documentation explaining the vague overall design goals
  of `vagrant-spk` from `docs/vagrant-spk/index.md` into the existing
  file, `docs/vagrant-spk/customizing.md` which allowed me to delete
  `docs/vagrant-spk/index.md` entirely.

- Adjust the packaging tutorial to say that some parts might be slow
  due to download times.

- Drastically improve (in my opinion) the amount of information, and
  its contextualization, within the Developer Portal. Up until now,
  Cap'n Proto was not even mentioned once.

- Update commented-out TODO items to indicate that some docs have now
  been written.

### CODE REVIEW

**Comment by paulproteus** [comment]
Screenshot of what this looks like. Going to self-merge now since this is 100% docs.

@neynah you might have thoughts and I'm happy to take time to respond to them. I made some guesses as to which image made sense; @neynah if you want to propose new images, I 100% endorse any suggestions you make, but I also think this is OK as-is for now.

screenshot from 2016-04-21 14 17 59

**Comment by paulproteus** [comment]
https://docs.sandstorm.io/en/latest/developing/ is the live page.

**Comment by neynah** [comment]
Nice! Yeah, I'll see if I can fix up some of the icons today. "App Market" should be capitalized but that's the only comment I have for now. I can submit the fix for it along with new icons.

**Comment by paulproteus** [comment]
Super rad. Thanks!​

**Pull request merged**
