### PR TITLE
Minor spelling fix

### PR DESCRIPTION
**Pull request by spollard**

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
Hmmm... interestingly enough, this could've be "once", or it could be "since"... I suspect the latter is a better fit but I'm okay either way.

**Comment by zenhack** [comment]
I agree; since is probably better but it doesn't seem super important.

**Comment by spollard** [comment]
Since sounds better. :)

**Comment by ocdtrekkie** [comment]
Okay, since everyone went with "since", I'm going to close this. @spollard if you want to send a PR for "since", I'll merge it, or if you don't, I will submit my own and coauthor you at some future point when I remember.

**Comment by spollard** [comment]
You got it. I don't really want to make a whole new PR...

**Comment by zenhack** [comment]
I approved @ocdtrekkie's other pr, though in the future a force-push is probably the right thing to do in this situation; a separate pr does feel a bit excessive.

**Comment by ocdtrekkie** [comment]
Post-mortem question: Should I have waited to close the PR longer? I definitely would've accepted a force-push to this PR and reopened/merged it. I also read @spollard's comment today as saying I should submit the fix, because he didn't want to, but that could've been incorrect in reading it that way.

I want to make sure I'm not being discouraging of contribution, if there's a different way I should've addressed this one, by all means call me out.

**Comment by zenhack** [comment]
I'll let @spollard weigh in if he wants on how he took that. But it usually doesn't make sense to open a new PR for changes, unless it's a large-ish patch that's a completely different approach to something.

**Comment by ocdtrekkie** [comment]
Indeed, though you cannot force push from the web UI, which is how I assume (perhaps erroneously, I grant) a "patch-5" branch was created. And I'd rather a fresh PR than a second commit in one PR.

**Comment by spollard** [comment]
You were right! I didn't really care how the fix got in.

**Pull request closed without merging**
