### PR TITLE
Remove two uses of "file" where we mean "grain"

### PR DESCRIPTION
**Pull request by paulproteus**
Ref #589

### CODE REVIEW

**Comment by paulproteus** [comment]
Garply, retest this please

**Comment by paulproteus** [comment]
The test failure here strikes me as very weird.

There's an image of the identity chooser, which seems totally OK to me.

**Comment by paulproteus** [comment]
Garply, retest this please

**Comment by paulproteus** [comment]
Garply, retest this please

**Comment by paulproteus** [comment]
It now *only* shows the one known-flaky test.

**Comment by paulproteus** [comment]
@kentonv this is now ready for your review/merge!

**Comment by paulproteus** [comment]
Thanks!

@neynah I think this is the last vestige of "file" over "grain".

**Comment by neynah** [comment]
@paulproteus I'm glad! :+1:

**Pull request merged**
