### PR TITLE
Automatically switch Sandcats users to Let's Encrypt over the next few weeks.

### PR DESCRIPTION
**Pull request by kentonv**
Each server will migrate at a random time between June 10 and June 23.

### CODE REVIEW

**Comment by kentonv** [comment]
@zenhack I had to revert the conversion of acme-dns-01-sandcats to ES module syntax. It turns out this broke it, because we dynamically `require()` these modules, and you can't `require()` an ES module, you have to import it. I tried using dynamic `import()`, but that didn't work either, saying the module wasn't found. I think Meteor may have some restrictions around dynamic imports, but instead of trying to figure it out, I reverted to what had been tested before.

It's tough to test this ACME stuff. I wonder if we could set up an integration test that uses the Let's Encrypt staging service somehow...

**Comment by ocdtrekkie** [comment]
Should we file an issue to delete all this code after the cutover is complete?

**Comment by kentonv** [comment]
@ocdtrekkie If you want, but deleting code is my favorite part, I'm not gonna forget about it. :)

**Comment by kentonv** [comment]
Also I definitely call dibs on the code deletion. :)

**Pull request merged**
