### PR TITLE
Use FontForge to convert SVGs to TTF

### PR DESCRIPTION
**Pull request by paulproteus**
- Also add this to `install.md`

- This fixes the "Where did the circle go?" problem in #2102

### CODE REVIEW

**Comment by paulproteus** [comment]
@zarvox requesting your +1/-1 on the requirement for any further docs/etc. changes.

I believe you said you already updated Jenkins, too?

**Comment by paulproteus** [comment]
BTW yes, this does successfully loudly fail if fontforge is misssing! :)

**Comment by zarvox** [comment]
+1, no additional requirements from me.

I've installed `fontforge` on build.sandstorm.io, yes.

Builds are a little backlogged at the moment, but the build server should be good to go for this change.

**Comment by dwrensha** [comment]
What is "the circle"?

This change makes me nervous because last time I played around with the fonticons, basically any configuration change I made would cause problems. So I just want to say: please make sure to test this throroughly.

**Comment by zarvox** [comment]
https://github.com/sandstorm-io/sandstorm/blob/master/icons/question.svg has a circle around a question mark.  Somehow, when using the node backend for the fonticon generation, it gets lost, and you just have the question mark.

**Comment by dwrensha** [comment]
On my Arch Linux box, this is my fontforge:

```
$ fontforge --version
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 13:54 TAHT  6-May-2016-ML-D.
 Based on source from git with hash: 
no xdefs_filename!
TESTING: getPixmapDir:/usr/share/fontforge/pixmaps
TESTING: getShareDir:/usr/share/fontforge
TESTING: GResourceProgramDir:/usr/bin
trying default theme:/usr/share/fontforge/pixmaps/resources
fontforge 13:54 TAHT  6-May-2016
libfontforge 20160506
```

and I get this error when I try to `make update` Sandstorm:

```
Running "webfont:icons" (webfont) task
Warning: Something went wrong when running fontforge. Probably one of your SVGs is too complicated for fontforge.

1. Try to use “node” engine instead of “fontforge”. (See “engine” option in the Readme.)

2. To find “bad” icon try to remove SVGs one by one until error disappears. Then try to simplify this SVG in Sketch, Illustrator, etc.

 Use --force to continue.

Aborted due to warnings.
make: *** [Makefile:259: shell/client/styles/_icons.scss] Error 6
```

**Comment by paulproteus** [comment]
I was just going to write you a message @dwrensha saying that I do plan to test this more thoroughly. 

FWIW this is my fontforge:

```bash
paulproteus@slittingmill:~/projects/sandstorm/shell$ fontforge --version
Copyright (c) 2000-2012 by George Williams.
 Executable based on sources from 14:57 GMT 31-Jul-2012-ML.
 Library based on sources from 14:57 GMT 31-Jul-2012.
fontforge 20120731
libfontforge 20120731-ML
```

I don't suppose it's easy for you to try to downgrade...?

**Comment by zarvox** [comment]
My fontforge on Fedora is unfazed by the current SVGs; version below:

```
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 09:36 UTC 26-Aug-2015-ML-D.
 Based on source from git with hash: 
no xdefs_filename!
TESTING: getPixmapDir:/usr/share/fontforge/pixmaps
TESTING: getShareDir:/usr/share/fontforge
TESTING: GResourceProgramDir:/usr/bin
trying default theme:/usr/share/fontforge/pixmaps/resources
fontforge 09:36 UTC 26-Aug-2015
libfontforge 20150826
```

That said, I am also experiencing the down-arrow being out of place, and the notification bell icon also appears to be missing (or vertically offset enough that it's not visible) now. :/

**Comment by zarvox** [comment]
My recommendation would be to revert this commit and live without the circle around the question mark until we can figure out what's going on there.

**Pull request merged**
