### PR TITLE
backups.md: Fixed 2 'sudo service' commands

### PR DESCRIPTION
**Pull request by elimisteve**

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by paulproteus** [comment]
Thanks @elimisteve ! This is great, and I'll merge it & deploy it.

**Comment by paulproteus** [comment]
Done!

**Comment by elimisteve** [comment]
@paulproteus :-) Thanks for the quick turn-around time; you guys are all over it!

**Pull request merged**
