### PR TITLE
Meteor testapp

### PR DESCRIPTION
**Pull request by zenhack**
This is a continuation of the work from #2939. It is still WIP; there is a test failure to debug. So far I have:

- merged in the latest changes from master
- re-keyed the app and included the key
- updated the version of meteor-spk
- incorporated some of @kentonv's suggestions re: the clean targets.

The test currently fails, with the app displaying this in the debug log:

```
Debug log: Untitled testapp instance
...** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2020-01-20T23:41:48.961+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
/programs/server/boot.js:356
}).run();
   ^

Error: The babel-runtime npm package could not be found in your node_modules
directory. Please run the following command to install it:

  meteor npm install --save babel-runtime

    at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)
    at fileEvaluate (packages/modules-runtime.js:197:9)
    at require (packages/modules-runtime.js:120:16)
    at packages/babel-runtime.js:139:15
    at packages/babel-runtime.js:150:3
    at /programs/server/boot.js:303:34
    at Array.forEach (native)
    at Function._.each._.forEach (/programs/server/node_modules/underscore/underscore.js:79:11)
    at /programs/server/boot.js:128:5
    at /programs/server/boot.js:352:5
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2020-01-20T23:41:50.576+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
/programs/server/boot.js:356
}).run();
   ^

Error: The babel-runtime npm package could not be found in your node_modules
directory. Please run the following command to install it:

  meteor npm install --save babel-runtime

    at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)
    at fileEvaluate (packages/modules-runtime.js:197:9)
    at require (packages/modules-runtime.js:120:16)
    at packages/babel-runtime.js:139:15
    at packages/babel-runtime.js:150:3
    at /programs/server/boot.js:303:34
    at Array.forEach (native)
    at Function._.each._.forEach (/programs/server/node_modules/underscore/underscore.js:79:11)
    at /programs/server/boot.js:128:5
    at /programs/server/boot.js:352:5
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2020-01-20T23:41:51.859+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
/programs/server/boot.js:356
}).run();
   ^

Error: The babel-runtime npm package could not be found in your node_modules
directory. Please run the following command to install it:

  meteor npm install --save babel-runtime

    at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)
    at fileEvaluate (packages/modules-runtime.js:197:9)
    at require (packages/modules-runtime.js:120:16)
    at packages/babel-runtime.js:139:15
    at packages/babel-runtime.js:150:3
    at /programs/server/boot.js:303:34
    at Array.forEach (native)
    at Function._.each._.forEach (/programs/server/node_modules/underscore/underscore.js:79:11)
    at /programs/server/boot.js:128:5
    at /programs/server/boot.js:352:5
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
```

It appears the app is not able to find one of its dependencies at run-time (namely `babel-runtime`). The resulting spk does contain the package somewhere:

```
$ find -name babel-runtime
./programs/server/npm/node_modules/babel-runtime
./programs/server/npm/node_modules/meteor/babel-runtime
./programs/server/npm/node_modules/meteor/babel-compiler/node_modules/babel-runtime
```

I haven't yet worked out why it can't find it.

### CODE REVIEW

**Comment by kentonv** [comment]
I've seen that error before when working on Sandstorm itself. Running the command suggested in the error message does seem to fix it in my experience. I guess maybe we need to run that automatically as part of the build process for the test app?

**Comment by zenhack** [comment]
So, I did the following:

- Hazily typed not quite the same command in the meteor-testapp directory: `npm install --save-dev babel-runtime` (note the `-dev` and the lack of `meteor`. I didn't sleep much last night).
- Ran the tests, past the babel error (see below).
- Realized that moving the library to `devDependencies` made no sense, reverted the change, tested again, still "fixed." -- but obviously some state has persisted.
- Did a `make clean` and generally attempted to clear out anything I could find.
- Still can't reproduce the above error, even with a clean source tree.

`meteor-spk pack` *does* run `meteor npm install`, which *should* be sufficient to pull in babel-runtime if its already in `dependencies` (which it was).

Would be interested to know if others can reproduce the error.

---

...with that out of the way :roll_eyes: I hit this error, which appears to be the same node-fibers/detect-libc problem we dealt with in #3178. I guess we could add the same hack to meteor-spk...

```
Debug log: Untitled testapp instance
...** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2020-01-26T14:40:05.576+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
## There is an issue with `node-fibers` ##
`/programs/server/node_modules/fibers/bin/linux-x64-57/fibers.node` is missing.

Try running this to fix the issue: node /programs/server/node_modules/fibers/build
/programs/server/node_modules/fibers/fibers.js:20
	throw new Error('Missing binary. See message above.');
	^

Error: Missing binary. See message above.
    at Object.<anonymous> (/programs/server/node_modules/fibers/fibers.js:20:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/programs/server/boot.js:1:75)
    at Module._compile (module.js:652:30)
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2020-01-26T14:40:05.938+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
## There is an issue with `node-fibers` ##
`/programs/server/node_modules/fibers/bin/linux-x64-57/fibers.node` is missing.

Try running this to fix the issue: node /programs/server/node_modules/fibers/build
/programs/server/node_modules/fibers/fibers.js:20
	throw new Error('Missing binary. See message above.');
	^

Error: Missing binary. See message above.
    at Object.<anonymous> (/programs/server/node_modules/fibers/fibers.js:20:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/programs/server/boot.js:1:75)
    at Module._compile (module.js:652:30)
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2020-01-26T14:40:06.301+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
## There is an issue with `node-fibers` ##
`/programs/server/node_modules/fibers/bin/linux-x64-57/fibers.node` is missing.

Try running this to fix the issue: node /programs/server/node_modules/fibers/build
/programs/server/node_modules/fibers/fibers.js:20
	throw new Error('Missing binary. See message above.');
	^

Error: Missing binary. See message above.
    at Object.<anonymous> (/programs/server/node_modules/fibers/fibers.js:20:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/programs/server/boot.js:1:75)
    at Module._compile (module.js:652:30)
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
```

**Comment by kentonv** [comment]
We're probably past due for a meteor-spk update anyhow.

**Comment by zenhack** [comment]
Hm, I think this is actually not the same issue; the filesystem layout is different, and there's no `*-57/`, but there are `-46/` and some other 40's; maybe that's a version number for something? I'm going to see about updating meteor-spk, and go from there.

**Comment by zenhack** [comment]
OK! I think this is working; tests pass on my machine now.

The `-57` and friends are node ABI versions. For some reason, with the upgrade to meteor-spk 0.4.1, it was pulling in a newer version of node, but still using the dev bundle from the old version of meteor. I reverted the meteor-spk version back to 0.3.2, which is what the pr had it at before, and it works.

We should update at some point, but this is feeling like too much yak shaving, and I'm inclined to suggest that that can happen in a separate pr.

**Comment by kentonv** [comment]
Nice!

**Pull request merged**
