### PR TITLE
Check for kernel version before user namespaces

### LINKED ISSUE #478: Installer: check kernel version before checking userns
We received a report that the installer complained about being unable to create user namespaces, but it turned out the user in question was using kernel version 3.10. Our installer is supposed to verify that the user is on 3.13 or newer, but I guess that check is occurring after the userns check? We should probably do the version check first, since it's simpler and more informative.

### PR DESCRIPTION
**Pull request by paulproteus**
This way, if someone has a Linux distribution that is too old to
run Sandstorm, we give them relevant advice.

Close #478

### CODE REVIEW

**Comment by paulproteus** [comment]
I'm running the installer tests locally (on my laptop) now.

**Comment by paulproteus** [comment]
I'm going to merge this as-is, since supposedly I own `install.sh` and `installer-tests/`.

**Comment by paulproteus** [comment]
@kentonv can you update `install.sandstorm.io` with the latest `install.sh`?

I should have tagged you on this when I merged it.

**Comment by kentonv** [comment]
Done

**Comment by paulproteus** [comment]
Yay thanks!

**Pull request merged**
