### PR TITLE
Somewhat clarify the prod-vs-dev choice in the install script.

### PR DESCRIPTION
**Pull request by dwrensha**
This step always makes me pause, because I'm like "I want a full development server so that I can hack on Sandstorm itself -- which option does that fall under?"

### CODE REVIEW

**Comment by kentonv** [comment]
@paulproteus

**Comment by paulproteus** [comment]
I don't love calling anything "production", because it's a term of art that relates to devops/sysadmining, and non-sysadmin users are not likely to find it meaningful.

I'm going to think aloud to see if I can revise it.

Options:

- A full production server with automatic setup (press enter to accept this default)

- A public-facing server with automatic setup (press enter to accept this default)

- A Sandstorm server with automatic setup (press enter to accept this default)

- A server you and others will use, with automatic setup (press enter to accept this default)

- A Sandstorm server to get work done (press enter and we'll guide you through setup)

- A Sandstorm server for productive use (press enter and we'll guide you through setup)

- A typical Sandstorm server (press enter and we'll guide you through setup)

**Comment by paulproteus** [comment]
- 1. A Sandstorm server to run apps (press enter to accept this default)

- 2. A development server, for writing apps or working on Sandstorm itself

---

- 1. A typical install, to use Sandstorm (press enter to accept this default)

- 2. A development server, for writing apps or working on Sandstorm itself

---

**Comment by paulproteus** [comment]
- A typical install, to use Sandstorm (press enter to accept this default)
- A development server, for working on Sandstorm itself or localhost-based app development

**Comment by paulproteus** [comment]
I'm going to close this now that #1712 has landed, which supercedes this. I'm open to further feedback, though!

**Pull request closed without merging**
