### PR TITLE
test if openssl is available

### PR DESCRIPTION
**Pull request by Finkregh**
this tests if openssl is available, which may be not ;-)

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by paulproteus** [comment]
Hi!​ Thanks for this pull request!

For what it's worth, we attempt to check for openssl's existence a few
lines above that, but we only do it in the case that the user is enabling
sandcats HTTPS and/or dyndns.

Do you know if the check that exists is enough? I figure it's not since
you're submitting this PR, but I don't see where the install would fail at
the moment, so I'm a little confused, and hoping you can explain!

Thanks,

Asheesh.

**Comment by paulproteus** [comment]
Oh, I see... we do the dependencies check before we know if the user is
going to pick sandcats!​

**Comment by Finkregh** [comment]
oh, my; i must have played around too much with my alpine linux-testbed...

**Comment by paulproteus** [comment]
Okay @Finkregh (-:

FWIW if it isn't enough, then do let me know! I am not convinced that install.sh is perfect; I know it's far from perfect!

**Pull request closed without merging**
