### PR TITLE
Add dev accounts

### LINKED ISSUE #150: Implement some sort of "local developer account" login
For the purpose of a localhost Sandstorm server that is only accessible to one person anyway and is intended only for development, it would make sense to implement some way to create test users and log in as them. This way, people don't have to hook Google or Github authentication just for their silly testing.

The feature should NOT use passwords or anything else that could be mistaken for security. The developer should be able to create as many users as they want and arbitrarily log in as any of them by just choosing the account from a list.

We can implement this pretty easily using the same approach as the "demo user" code.

### PR DESCRIPTION
**Pull request by jparyani**
This uses a new sandstorm.conf setting named ALLOW_DEV_ACCOUNTS. If set to true, there will be a new Meteor login service named DevAccounts, and clicking it will direct you to a page where you can login as your choice of Alice, Bob, or Carol. Alice will always be an admin.

Fixes #150

### CODE REVIEW

**Comment by paulproteus** [comment]
I am excited about this. If the target users are app developers, this seems
perfectly great as an idea.

If the target is self installers using their apps for real, I would rather
see an approach where the user enters an email address and we log them in,
via a new hypothetical flow that I nickname, Password reset as login.

I am typing on a phone so apologies if this comes off as short. I can try
to explain more in a bit.

**Comment by jparyani** [comment]
Ya the target audience here is developers that don't want to bother setting up a real authentication method for a local server. It should never be used in production.

**Comment by paulproteus** [comment]
Cool, though I do wonder if even they would be better off with the password
reset as login flow, if the installer asks for an email address, and prints
out a token, and then you can use that to log in.

Then again, my proposal doesn't help simulate Bob and Charlie. OK, I like
your idea now!

**Comment by jparyani** [comment]
Now it will purge dev users if a server ever switches allowDevAccounts to false, and dev users also play nicely with the auto-admin logic in Sandstorm.

**Comment by kentonv** [comment]
Hmm, I think if we're purging the users we'll also need to purge their grains and possibly other things. Maybe we need a purgeUser() function defined in db.js, so it can be extended whenever there's a new collection to purge. I guess it also needs to delete the grains on disk. Ugh.

Alternatively, we could change the page wording so that it doesn't promise that dev accounts will go away if you change the flag. I don't think there's much of a user case for taking a dev server and switching it to prod -- there's a lot of ways that could go badly, I suspect, so we probably shouldn't encourage it.

**Comment by jparyani** [comment]
Ping @kentonv.

I went with the easy solution and removed the text that said it was safe to switch to ALLOW_DEV_ACCOUNTS=false after it's been true.

**Pull request merged**
