### PR TITLE
Change Developer portal to Developer hub

### PR DESCRIPTION
**Pull request by neynah**

### CODE REVIEW

**Comment by paulproteus** [comment]
Can you also adjust `README.md` accordingly?

FWIW I found that by running this command.

```
git grep -i 'Developer portal'
```

**Comment by paulproteus** [comment]
If you want to make the change to `README.md` in a separate pull request, or tell me to do it, just let me know.

**Comment by neynah** [comment]
Okay, I edited the README.md as well. Let me know if there is anything else.

**Comment by paulproteus** [comment]
I'm merging this  because it's 100% docs!

**Comment by paulproteus** [comment]
Perfect. Thanks! Deployed.​

**Pull request merged**
