### PR TITLE
Provide a warning to admins when WebSockets are broken

### PR DESCRIPTION
**Pull request by paulproteus**
Refs #1694 #708 #504

### CODE REVIEW

**Comment by paulproteus** [comment]
Here's what it looks like when you get both warnings:

screenshot from 2016-03-23 19 04 30

If you want to imagine what it's like to get just this one warning, pretend it's the only one there!

**Comment by paulproteus** [comment]
FWIW, the purpose of this pull request is to be a quick hack that people hopefully see. I would perhaps be happier with a fix that makes a real "Notification", but I think this is 100% worth merging as-is for now. cc: @jvasile

**Comment by paulproteus** [comment]
@kentonv ready for your review/merge. Not necessarily urgent, but it's always easier to address feedback sooner rather than later.

**Comment by kentonv** [comment]
Please let your editor know not to insert tabs. :)

I fixed it for this PR, so merging now.

**Pull request merged**
