### PR TITLE
Add Finnish translation to Sandstorm

### PR DESCRIPTION
**Pull request by xet7**
Added Finnish translation to Sandstorm.

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
i,i it's awesome to see another localization for Sandstorm.

**Comment by kentonv** [comment]
Nice!

My grandparents on my mother's side immigrated from Finland. Unfortunately I don't know the language myself, but I'm still extra-happy to see this.

**Comment by xet7** [comment]
@kentonv 

How can I test this? Will it be included to Sandstorm release sometime?

**Comment by kentonv** [comment]
@xet7 To test now you'll need to build from source:

https://docs.sandstorm.io/en/latest/install/#option-4-installing-from-source

It would be great if you could do that to verify your translation before it's released.

I will probably do the next release around Jan 6, or maybe Jan 13.

**Comment by xet7** [comment]
@kentonv 

Ok I will install from source and test it.

**Comment by xet7** [comment]
@kentonv 

I did compile Sandstorm on Pop!_OS 64bit that is based on Ubuntu 17.10.

I will later send fixes to this Finnish translation, to use better words.

Not everything is translated, for example when installing Wekan some popups/tooltips were in English. Are there translations also in other places? Is App Market content also translatable, where new apps are installed from? Is it possible to translate Sandstorm website?

**Comment by ocdtrekkie** [comment]
The Sandstorm App Market should be pretty trivial to translate. Ideally for simplicity we'd want to use the same i18n package on this Meteor app: https://github.com/sandstorm-io/sandstorm-app-market

The App Market has not a whole ton of text of it's own, so I shouldn't think this would be a huge project. Most of the issue is that the App Market's apps all have text, which currently doesn't localize, even though there exists a design to do so.

If you look at Wekan's pkgdef, Maxime had put in some of the French translations, including a very outdated changelog in French: https://github.com/wekan/wekan/blob/devel/sandstorm-pkgdef.capnp and https://github.com/wekan/wekan/blob/devel/meta/t9n-changelog/fr.md

**Comment by ocdtrekkie** [comment]
This is the PR that added tap:i18n to Sandstorm itself: https://github.com/sandstorm-io/sandstorm/pull/2985 and the first commit is really, most of the change from a technical standpoint. The rest of that giant PR is string replacement.

**Comment by ocdtrekkie** [comment]
Note that translating the main sandstorm.io website would be very much not even remotely trivial. The sandstorm.io website is mostly static html, and many of the images contain text.

**Comment by kentonv** [comment]
@xet7 Sandstorm's i18n is definitely incomplete. The i18n hooks were added in #2985, but not everything was hooked. I'm happy to accept PRs to add more hooks.

I'd also be happy for someone to take over the app market and add i18n hooks there, though as Jake points out the app descriptions come out of the app packages and so won't be translated unless the package maintainer adds translations. There is indeed support in the metadata structures for specifying translations, although I suspect the way it's done currently isn't very maintainable -- it's organized by message rather than by language, which probably means it'll be a mess for anyone supporting more than a couple languages. We should probably develop a better way for apps to provide separate translation tables, but that's a big project.

Regarding the Sandstorm web site, I'd rather not try to translate it currently, as doing so would make it pretty difficult for me to make changes to the site going forward -- and the site is currently in need of an overhaul to make it less commercial.

**Comment by ocdtrekkie** [comment]
I'm gonna tag @caasi and @urakagi in here since they implemented localization of Sandstorm itself. Either or both of them might be interested in implementing the same for the app market, perhaps?

**Comment by urakagi** [comment]
I'm not sure about the structure of the app market. Is it as same as Sandstorm shell so add tap-18n and modifying templates will do the work?

**Comment by ocdtrekkie** [comment]
Should be more or less the same thing, yeah. AFAIK, there's also massively less text in the app market. Most of the text in it comes from the app packages themselves.

**Pull request merged**
