### PR TITLE
Add stats

### PR DESCRIPTION
**Pull request by jparyani**

### CODE REVIEW

**Comment by jparyani** [comment]
Done. Also added stats for packages.

**Comment by jparyani** [comment]
Done (went with the 2nd method of storing appIds on appDemo account creation).

**Comment by kentonv** [comment]
FYI: I'm changing the computeTime to be at the recordStats level rather than the computeStats level.

**Comment by kentonv** [comment]
Also renaming `packages` to `apps` since it's a table by app ID, not package ID. :)

**Comment by kentonv** [comment]
See a0223ef -- let me know if there's anything wrong.

**Pull request merged**
