### PR TITLE
Update nl.i80n.json

### PR DESCRIPTION
**Pull request by FreekDankelman**
Dutch translation

### CODE REVIEW

**Comment by xet7** [comment]
In my Finnish translation I did translate "Grains" to "Jyvät", because for Finnish speaking people it's easier to understand, and that word in English is not in common use. At Finland farmers use grains and land to grow some stuff. For me, grain is Sandstorm-style container, similar to Docker and Snap, with a difference that grains are only running when someone uses them.

**Comment by ocdtrekkie** [comment]
@xet7 I think it may make sense to defer to a given translator on whether or not to translate certain terms, like Sandstorm and grain. Different locales may sway different ways on the matter.

**Comment by xet7** [comment]
@ocdtrekkie 

Yes, it's a decision by the translator of course. It depends on culture, etc, what words are in use in each country.

**Comment by kentonv** [comment]
Thanks!

**Pull request merged**
