### PR TITLE
Remove appTitle prompt at top of screen

### LINKED ISSUE #2060: On app install page: Remove top "Install {{appName}}?" question
Rationale: The question is embedded within the button at the bottom.

### PR DESCRIPTION
**Pull request by paulproteus**
Close #2060

### CODE REVIEW

**Comment by paulproteus** [comment]
Screenshots from after this change:

screenshot from 2016-06-08 17 03 04

screenshot from 2016-06-08 17 03 09

**Comment by paulproteus** [comment]
I just adjusted the PR now. New screenshot attached. @neynah requesting your +1 -1.

screenshot from 2016-06-17 13 47 09

**Comment by neynah** [comment]
+1! Great. :D

**Comment by paulproteus** [comment]
Great. Requesting review/merge from @kentonv.

**Comment by kentonv** [comment]
BTW did you test the mobile view? Just checking.

**Comment by paulproteus** [comment]
@kentonv I did not! I will shrink my browser window and test this.

**Comment by paulproteus** [comment]
The PGP key fingerprint is too wide but otherwise this is OK IMHO. I'll submit a follow-up PR focused on allowing word wrap within the fingerprint.

key-too-wide

**Pull request merged**
