### PR TITLE
Add initial version of organizational user management

### PR DESCRIPTION
**Pull request by jparyani**

### CODE REVIEW

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Okay, this failure happened twice, though I'm not sure what happened to cause it:

```
Exception while invoking method 'newGrain' Error: Match error: Expected string, got object
    at check (packages/check/packages/check.js:41:1)
    at [object Object].Meteor.methods.newGrain (server/proxy.js:238:5)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
    at livedata_server.js:704:46
    at tryCallTwo (/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
    at doResolve (/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
Sanitized and reported to the client as: Match failed [400]
```

**Comment by jparyani** [comment]
There was a subtle error in how demo users were being checked that was annoyingly difficult to track down. Should be fixed now.

**Comment by kentonv** [comment]
It looks like currently this feature is not gated by the feature key. Now that feature keys are implemented, can we add that to this PR?

**Comment by jparyani** [comment]
Ready to merge

**Comment by kentonv** [comment]
I merged this and reverted 93388cf because I actually think the code as you had it originally was cleaner, and my request that prompted the change was based on a misunderstanding.

**Pull request merged**
