### PR TITLE
correction of the French translation

### PR DESCRIPTION
**Pull request by jeau**
with this PR could you add the contribution of Benoit Renault to the french translation inside the changelog of v0.224 (2018-01-06)  ? 
Thanks

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
@jeau IMHO, go ahead and add a commit to this branch doing so. Then Kenton doesn't have to remember to do so.

**Comment by jeau** [comment]
@ocdtrekkie I don't have write access to sandstorm repo

**Comment by ocdtrekkie** [comment]
@jeau If you add a commit to the branch of your PR request (sandstorm-fr:master), it should add the commit to this pull request.

**Comment by jeau** [comment]
the last two commits fix two display bugs in the administration page of each user's role, 

see the screenshot.
capture d ecran 2018-01-16 a 23 51 18

**Comment by kentonv** [comment]
Thanks, and sorry for messing up the attribution!

**Pull request merged**
