### PR TITLE
.gitignore vim swapfiles

### PR DESCRIPTION
**Pull request by zarvox**

### CODE REVIEW

**Comment by paulproteus** [comment]
FWIW in the past, Kenton has been -1 on these PRs to add stuff to
.gitignore to minimize "git status" noise. If he's still -1, then at least
I should document that somewhere, e.g.
https://github.com/sandstorm-io/sandstorm/wiki/Pull-Request---Code-Review-Procedure
or within .gitignore as a comment.

I, for one, love these .gitignore PRs, but I can deal with whatever we go
with.

**Comment by zarvox** [comment]
Sure, feel free to close the PR if this is undesired.

**Comment by kpreid** [comment]
Tip: If your choice of editor, operating system, etc. creates files that make sense to ignore, you can do that locally using `git config [--global] core.excludesfile <path to your own ignore file>`

**Comment by kentonv** [comment]
My issue with these is that I kind of want `git status` to tell me if there is litter laying around, especially in the source directories where Ekam / Meteor scan all files and potentially do things with them.

**Comment by zarvox** [comment]
Fair enough.  I'll deal. :)

**Pull request closed without merging**
