### PR TITLE
Replace svg icons with an autogenerated webfont

### PR DESCRIPTION
**Pull request by jparyani**
I've replaced the notification bell icon as an example of how this should be used.

There's some small stylistic things that I'm open to changing.

1. The icon classes are prefixed by default with `icon_` (eg. `icon_notification`). By convention, I think we have been using `-` instead of `_` in CSS.
2. I'm using a mixin for `webfont-icon`. This is a little inefficient, but I'm not sure how to cleanly do this with an extend instead.

### CODE REVIEW

**Comment by kentonv** [comment]
This is disturbingly simple.

I would indeed slightly prefer `-` rather than `_` in class names. Is that actually possible to change? I don't see the prefix specified anywhere.

I think that the things you've named "sandstorm-icons" should probably just be called "icons"; "sandstorm" is redundant.

The test failure looks possibly legit.

**Comment by jparyani** [comment]
Test failure fixed and comments addressed. It turned out pretty easy to to change `_` to `-` in the `templateOptions` of grunt-webfont.

**Comment by dwrensha** [comment]
This adds a build-time dependency on npm. Is that necessary? If so, it should be added to the list of dependencies here: https://docs.sandstorm.io/en/latest/install/#option-4-installing-from-source

**Comment by dwrensha** [comment]
Or can we maybe use an npm that comes with Meteor?

**Comment by dwrensha** [comment]
This also requires node to be installed:

```
cd icons && npm install
npm WARN package.json sandstorm-fonts@0.1.0 No repository field.
npm WARN package.json sandstorm-fonts@0.1.0 No README data
npm WARN deprecated exec@0.1.4: deprecated in favor of builtin child_process.execFile
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.25","npm":"1.4.21"})
grunt-cli@0.1.13 node_modules/grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.7)
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)

grunt@0.4.5 node_modules/grunt
├── which@1.0.9
├── dateformat@1.0.2-1.2.3
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── rimraf@2.2.8
├── colors@0.6.2
├── async@0.1.22
├── grunt-legacy-util@0.2.0
├── hooker@0.2.3
├── nopt@1.0.10 (abbrev@1.0.7)
├── exit@0.1.2
├── lodash@0.9.2
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── glob@3.1.21 (inherits@1.0.2, graceful-fs@1.2.3)
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.7.0)
├── js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.16)
├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.2)
└── grunt-legacy-log@0.1.2 (grunt-legacy-log-utils@0.1.1, underscore.string@2.3.3, lodash@2.4.2)

grunt-webfont@0.4.8 node_modules/grunt-webfont
├── exec@0.1.4
├── async@0.9.2
├── temp@0.8.3 (os-tmpdir@1.0.1, rimraf@2.2.8)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── ttf2eot@1.3.0 (argparse@0.1.16)
├── underscore.string@2.3.3
├── ttf2woff@1.3.0 (argparse@0.1.16, pako@0.2.8)
├── glob@4.0.6 (inherits@2.0.1, graceful-fs@3.0.8, minimatch@1.0.0, once@1.3.2)
├── svg2ttf@1.1.2 (svgpath@1.0.7, xmldom@0.1.19, argparse@0.1.16, lodash@2.1.0)
├── lodash@2.4.2
├── svgicons2svgfont@0.1.1 (sax@0.6.1, readable-stream@1.1.13, svg-pathdata@0.0.6)
└── winston@0.7.3 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, colors@0.6.2, async@0.2.10, pkginfo@0.3.1, request@2.16.6)
cd icons && ./node_modules/.bin/grunt
/usr/bin/env: node: No such file or directory
Makefile:234: recipe for target 'shell/client/_icons.scss' failed
make: *** [shell/client/_icons.scss] Error 127
```

**Comment by paulproteus** [comment]
+1 to borrowing Meteor's npm/node

**Pull request merged**
