### PR TITLE
Noticed a missing link

### PR DESCRIPTION
**Pull request by JonTheNiceGuy**

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by paulproteus** [comment]
This looks great. Merging now!

**Comment by paulproteus** [comment]
Thanks for finding this & fixing it, @JonTheNiceGuy !

**Comment by paulproteus** [comment]
https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial/ is now up to date with this change.

**Pull request merged**
