### PR TITLE
Wording after app is installed

### PR DESCRIPTION
**Pull request by JamborJan**
It used to say `Click "My Files" to create a new file`but now its `Click "New..." to create a new file` after the UI rework.

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by paulproteus** [comment]
Garply, ok to test

**Comment by paulproteus** [comment]
Looks great. I'll make sure it passes the tests.

**Comment by paulproteus** [comment]
Garply, ok to test

**Pull request merged**
