### PR TITLE
do not merge: test commit to trigger Jenkins doing PR testing.

### PR DESCRIPTION
**Pull request by zarvox**
This is just a test PR to see if my Jenkins job refactoring worked correctly, or if I'll have to try something else to parameterize the GitHub pull request builder context.

### CODE REVIEW

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by paulproteus** [comment]
_ooh_ a `js-style` check!

**Comment by paulproteus** [comment]
If it's possible to have an `installer-tests` check... maybe I should have that thing check if this commit modifies `install.sh` and then run `installer-tests`...!

**Comment by zarvox** [comment]
That could potentially be split out, yes.

I'm struggling to get Jenkins to update the commit status as it runs the test in question - seems one codepath wants to use the revision under test (the merge commit) and one codepath wants to use the pull request's HEAD.  Only the latter produces useful output.

For instance, as I write this, tests are running at https://build.sandstorm.io/job/Sandstorm%20PRs%20-%20build/9/console , but you do not see them in the commit status section of the UI.

But at the end of the test run, it will successfully update the status.

**Comment by zarvox** [comment]
I think I'm going to take a break from fiddling with Jenkins for the night and verify that the old tests are still in working order.

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
**clears throat** I said, Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
I'm satisfied with Jenkins' current state now.

**Comment by kentonv** [comment]
Man, Garply got a workout. Hope he lost some weight.

**Pull request closed without merging**
