### PR TITLE
Graphics for referral program

### PR DESCRIPTION
**Pull request by neynah**
For @paulproteus's referral program page. Edge graphic is to be placed on the very left and right sides of the referral banner (background-color: #6d5eb7)

### CODE REVIEW

**Comment by paulproteus** [comment]
FWIW:

I'm going to merge this into my local dev environment first, then submit a pull request that contains this commit _and_ other commits on top of it that use these SVG files.

**Comment by paulproteus** [comment]
@neynah question for you:

- sometimes you write `30GB` (no space) and sometimes you write `2 GB` (space). Should I be consistent and always do space, or consistent and always do no space, or follow your mockup precisely?

I might have other questions; I'll ask them here so there's clear documentation of the answers.

**Comment by paulproteus** [comment]
- I can't tell if the big-popping "30GB" is: (a) bold (b) font-size: 150% (c) ??

I'm going to go with bold *and* font-size: 150% and you can tell me if you like that, but if you already know, then let me know.

**Comment by paulproteus** [comment]
- Your sidebar in the mockup is less wide than the sidebar in actual Sandstorm, so I can't use it as a sizing guide, which is sad for me.

**Comment by paulproteus** [comment]
- You've collapsed the "Successful referrals" list from a bulleted list into a one-line comma-separated list. Is this change important? I'm going to assume yes, but I wanted to check.

**Comment by paulproteus** [comment]
FWIW, I've interpreted the padding of the white-background section as:

```
    padding-left: 50px;
    padding-right: 50px;
    padding-top: 40px;
    padding-bottom: 75px;
```

based on using this "ruler" tool to measure the image: https://chrome.google.com/webstore/detail/page-ruler/jlpkojjdgbllmedoapgfodplfhcbnbpn/related?hl=en

**Comment by paulproteus** [comment]
You've omitted the link in "open any grain" (within "To get started, open any grain and click Share access"). This seems like a decrease in functionality, but I'll go with omitting the link for now to be consistent to your mockup.

**Comment by paulproteus** [comment]
You've removed the bold text and period at the end of the sentence in "Once you send a sharing link out, people will appear in this list after they sign in.". I'm going to put the period back in but remove the bold text, but let me know if that is/isn't what you want.

**Comment by paulproteus** [comment]
Your mockup removed the link on the text "upgrade your account" within the text "If you need even more space, upgrade your account" but I think that link is important so I've retained it. Let me know if I should do otherwise.

**Comment by paulproteus** [comment]
This is what it looks like now:

screencapture-localhost-6080-referrals-1450309854439

**Comment by neynah** [comment]
Nice job @paulproteus. Also, based on your comments I will aim for less ambiguity and improve my mock-ups with additional notes and spend more time to look things over more carefully (to save time and reduce errors.) Feel free to also use your judgment if something seems/feels better to you.

**Comment by paulproteus** [comment]
Cool. FWIW I'm pretty OK with leaving notes like that and making decisions
myself, then going over the decisions with you before trying to merge
something. I don't need the mockups to be pixel-perfect, or buttressed with
paragraphs of explanation, so long as I can reach you after attempting to
understand them.

I was a bit frustrated that I couldn't make this 100% awesome on all
browser widths, but I think that's life.

**Pull request closed without merging**
