### PR TITLE
Group membership check in readConfig (fixes #711)

### LINKED ISSUE #711: Running sandstorm admin-token as non-privileged user crashes
Should probably offer a user-readable error "Run as root user or under sudo"

```
$ sandstorm admin-token
*** Uncaught exception ***
sandstorm/util.c++:47: failed: open(name.cStr(), flags, mode): Permission denied; name = ../var/sandstorm/adminToken
stack: 0x541e08 0x541d89 0x541d7a 0x5143a1 0x515025
```

### PR DESCRIPTION
**Pull request by mrdomino**
Testing: tried running `sandstorm admin-token` as root with a SERVER_USER, and as non-root with a matching uid, and with a different uid that was a supplementary member of SERVER_USER's group (passes the check in all cases), and with a different uid that was not a member (fails the check).

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by mrdomino** [comment]
Updated: I now default config.uids to the current user's uid/gid. Testing, in addition to the above: verified that `sandstorm admin-token` with no SERVER_USER passes for a non-root user.

**Comment by kentonv** [comment]
Why do all this work instead of calling `access()`?

**Comment by mrdomino** [comment]
I was concerned about possible cases like calling sandstorm without a var/sandstorm at some point -- maybe a hypothetical sandstorm install or something. But just calling access definitely feels better to me than running through gids. So if we can rely on ../var/sandstorm existing and having correct permissions, then I'll happily resubmit with that approach.

**Comment by mrdomino** [comment]
I went and did it anyway: https://github.com/sandstorm-io/sandstorm/pull/1617. Yeah, way simpler.

**Comment by kentonv** [comment]
Closing this since I like the access() approach better. Thanks!

**Pull request closed without merging**
