### PR TITLE
Add base href tip as per @paulproteus

### PR DESCRIPTION
**Pull request by audreyt**
https://github.com/audreyt/ethercalc/issues/240#issuecomment-135325954

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by paulproteus** [comment]
Garply, ok to test

**Comment by paulproteus** [comment]
The automated tests don't actually test documentation, but I love seeing green checkmarks.

**Comment by paulproteus** [comment]
To be pedantic, the BASE TARGET stuff doesn't affect the Sandstorm "static publishing" functionality, but the `app-iframe` of each grain. I'll see if I can figure out a better place to suggest placing this text tomorrow morning, as part of suggesting improvements to this pull request, and hold off on merging for now.

**Comment by paulproteus** [comment]
Hi @audreyt,

I think what I will do is merge this and then move the content to https://docs.sandstorm.io/en/latest/developing/troubleshooting/ ("Troubleshooting") for now.

Thanks for submitting it.

**Comment by paulproteus** [comment]
@audreyt I've merged this change as well as a few others and it's now at https://docs.sandstorm.io/en/latest/developing/troubleshooting/ 

Thank you for writing it!

**Pull request merged**
