### PR TITLE
don't serve web publishing requests from trashed grains

### LINKED ISSUE #2739: grains in trash can still serve public static content from /var/www
When a grain is in the trash, any content it has published should no longer be publicly available.

### PR DESCRIPTION
**Pull request by dwrensha**
Fixes #2739.

### CODE REVIEW

**Comment by kentonv** [comment]
Not sure how I missed this when doing code reviews last week. Sorry!

But looking at the code, it seems it won't work correctly on Blackrock where there are multiple frontend replicas. Is it worth a Mongo subscription to watch for changes? Not sure.

**Comment by zenhack** [comment]
Is this fix still applicable? There are some conflicts in pre-meteor.js, but I don't know if those are serious or just incidental.

Maybe @kentonv's comment about blackrock is no longer relevant, since Oasis is gone?

**Comment by zenhack** [comment]
...or is alpha running blackrock?

**Comment by ocdtrekkie** [comment]
Nope, Alpha is ordinary Sandstorm. Predates Blackrock entirely.

**Comment by ocdtrekkie** [comment]
@zenhack If we want to implement this, we should also would need to fix it after #3231.

**Comment by kentonv** [comment]
I suspect this PR would need to be completely rewritten due to the gateway having been moved to C++.

**Comment by zenhack** [comment]
Ok, yeah looking a bit more careful much of the code it's touching doesn't really exist any more (even though it's not touching the gateway directly); we should probably close this.

**Pull request closed without merging**
