### PR TITLE
Update apache-virtualhost.conf to include SSL conf

### PR DESCRIPTION
**Pull request by gah242s**
Having spent far too much time working on the wrong aspects while trying to get a purchased SSL certificate working, here's what I would have expected this file to look like.  As most people who will see this example are trying to implement an HTTPS installation, I believe it would be useful to have this match the layout of the NGINX example.

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by kentonv** [comment]
Neat!

@paulproteus, do you have an opinion about whether this is the right way to document this?

**Comment by gah242s** [comment]
Any reason this isn't pulled yet.

**Comment by ocdtrekkie** [comment]
@gah242s I would assume it fell somewhere between "paulproteus was asked for an opinion" and "paulproteus didn't offer up an opinion". :/ Perhaps the new notifications here will put it back on Kenton's radar for an upcoming weekend.

**Comment by paulproteus** [comment]
This looks very reasonable to me! Thanks @ocdtrekkie for the fresh comment here.

I haven't tested it, but I'm +1 on merging it as-is. @gah242s hopefully you've tested it :) and if not, I guess we'll find out when someone files an issue. It looks totally good to me.

**Comment by paulproteus** [comment]
And @gah242s - thanks for following the example of that nginx conf :D

**Comment by paulproteus** [comment]
And for submitting this patch, btw! Cheers.

**Comment by gah242s** [comment]
If running daily counts as a test, yes.

**Comment by kentonv** [comment]
Sorry for the long delay. Thanks for contributing this!

**Pull request merged**
