### PR TITLE
Migrate all docs from wiki

### PR DESCRIPTION
**Pull request by paulproteus**

### CODE REVIEW

**Comment by kentonv** [comment]
I think you own this so feel free to merge. :)

My main comment is, as I said before, we should try to separate the API features from the core packaging guide, to make packaging look less daunting. But it would be nice to have nesting, so that the top-level sections are still "using", "developing", "administrating".

**Comment by paulproteus** [comment]
Garply, retest this please

**Comment by paulproteus** [comment]
+1​

I will look into that in the fullness of time.

**Comment by paulproteus** [comment]
Garply, retest this please

**Pull request merged**
