### PR TITLE
More sensible text in share-access popup for various corner cases.

### PR DESCRIPTION
**Pull request by dwrensha**
Fixes https://github.com/sandstorm-io/sandstorm/issues/1065 and https://github.com/sandstorm-io/sandstorm/issues/1869.

### CODE REVIEW

**Comment by dwrensha** [comment]
If you do not have permission to access the grain, the popup looks like this:
loggedout

If you are not logged in and the grain is using the old sharing model, the popup looks like this:
public

**Comment by zarvox** [comment]
Thanks for looking into this. :)

Does it perhaps make more sense to hide the Share access button (and the webkey button?) entirely in these cases (or at least in the unauthorized-to-access-grain case)?  We already remove the rest of the grain-specific options in the toolbar that you can't make any use of if you're not the grain owner.

(Happy with the outcome either way.)

**Comment by dwrensha** [comment]
I do think it makes more sense to hide the buttons. I've added a commit which does that.

**Comment by paulproteus** [comment]
I would like to remark that this patchset is making my day. Yippee!

**Pull request merged**
