### PR TITLE
Add EXPERIMENTAL flag for getting HTTPS certs during install

### PR DESCRIPTION
**Pull request by paulproteus**
DONE:

* Write tests

DOING NOW:

* Verify that this passes the existing tests

### CODE REVIEW

**Comment by paulproteus** [comment]
@kentonv please review whenever you get a chance. Per https://github.com/sandstorm-io/sandstorm/wiki/Pull-Request---Code-Review-Procedure I'm the owner of the install script, but I'm happy to wait until e.g. Friday evening for your review before doing a self-merge.

**Comment by paulproteus** [comment]
BTW, all -- if you're reading this and wondering if this will give you working HTTPS certificates for your sandcats domain that browsers will trust -- it won't, alas.

More work be done before that is true!

**Comment by kentonv** [comment]
Seems fine to me.

**Comment by paulproteus** [comment]
:tada:

I look forward to Jenkins testing this!

**Comment by paulproteus** [comment]
Oh and now, hilariously, I'll get an email every time Jenkins runs the tests, because GlobalSign will email me saying a certificate (for the test domain) was successfully produced.

**Pull request merged**
