### PR TITLE
Remove comment in indexer.c++

### PR DESCRIPTION
**Pull request by Sprial404**

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by dwrensha** [comment]
Good find @Sprial404, and well played @kentonv!

Apparently https://github.com/sandstorm-io/sandstorm/pull/685 is the pull request where this was sneaked in.

**Comment by Sprial404** [comment]
I was just looking at how they used Capn'proto in a commercial project. And after looking through some of the code, I stumbled unto that comment.

**Comment by kentonv** [comment]
Hah! Length of time that this comment existed in the repository: one year, seven months.

@Sprial404, please e-mail kenton@sandstorm.io with your shirt size and shipping address. :) Also let me know if you'd prefer a Cap'n Proto t-shirt rather than Sandstorm -- we have both.

**Pull request merged**
