### PR TITLE
Acknowledge LibreBoard rename into Wekan in docs

### PR DESCRIPTION
**Pull request by mquandalle**

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by paulproteus** [comment]
Thanks @mquandalle . I'm going to merge this as-is, since it only touches documentation.

@kentonv if you're willing to (admittedly after-the-fact) +1 the README change, I'd appreciate it.

**Comment by paulproteus** [comment]
Thanks @mquandalle for taking care of this! We really should have done this ourselves.

**Comment by mquandalle** [comment]
Thanks for merging. We should also fix the LibreBoard occurrence on the Sandstorm website ([here](https://github.com/sandstorm-io/sandstorm-website/blob/47ec4064c33c34b56c066d59221695c23b8be0a3/index.html#L56), but I'm too lazy to create a PR ;-)

**Comment by kentonv** [comment]
+1

**Pull request merged**
