### PR TITLE
prepend '/' to paths in ExternalWebSessionImpl

### PR DESCRIPTION
**Pull request by dwrensha**
The `path` parameter to `WebSession`'s methods should never include the leading `'/'`. (See [this](https://github.com/sandstorm-io/sandstorm/blob/v0.196/src/sandstorm/web-session.capnp#L98-L99) and [this](https://github.com/sandstorm-io/sandstorm/blob/v0.196/shell/server/proxy.js#L1863).)

In contrast, the `path` argument in a call to node's [`http.request()`](https://nodejs.org/api/http.html#http_http_request_options_callback) should have a leading `'/'`. So  this pull request adds it.

I noticed this problem when I tried making a hacky HTTP pseudodriver by copying this code.

### CODE REVIEW

**Comment by jparyani** [comment]
Unfortunately, there are now apps that rely on the formerly buggy behavior. You'll have to check and handle both cases I think.

**Comment by dwrensha** [comment]
what apps use this?

**Comment by jparyani** [comment]
Specifically, our internal dashboard does. Beyond that, I'm not sure, but it is a public API that anyone could have used about a year+.

That being said, I did fix a major breaking issue in it a couple months back, and no one had complained about it not working, so maybe we are the only consumer.

**Comment by kentonv** [comment]
Should we temporarily add the '/' only if it doesn't exist, and then update the dashboard app, and then change the logic to always add it?

**Comment by dwrensha** [comment]
OK, I've added the temporary compatibility hack.

**Pull request merged**
