### PR TITLE
About us sandcat and sandstorm gradient logo

### PR DESCRIPTION
**Pull request by neynah**

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
May I recommend: https://github.com/sandstorm-io/logos

**Comment by paulproteus** [comment]
: D


I _think_ Kenton said we should retire the "logos" repo and use
sandstorm-website for logos we want to share? Let me see if I can
confirm/deny that.

If so, fair warning, I'll go delete the "logos" repo!

**Comment by kentonv** [comment]
These particular images are specifically for use inside the Sandstorm interface.

**Comment by ocdtrekkie** [comment]
It would be nice to have such things somewhere central though, even if it's moving the logos repo to the sandstorm-website\logos folder. SVG for the Sandstorm logo and stuff is good to be able to easily find.

**Pull request merged**
