### PR TITLE
Add vagrant-spk packaging tutorial and use mkdocs

### PR DESCRIPTION
**Pull request by paulproteus**
The primary purpose of this pull request is to store a vagrant-spk
packaging tutorial somewhere that people can find it. It also creates
a structure for future Sandstorm documentation, organized similarly
to the Django documentation.

If you have mkdocs installed, you can generate HTML based on this
by being in the Sandstorm directory and running:

`mkdocs`

@kentonv I'm hoping to merge this before the meetup tomorrow. If you're
willing to merge it today, that'd be great.

I haven't dug into creating `docs.sandstorm.io` yet; I hope to do that tomorrow,
but it's not a showstopper for what I need for the meetup.

### CODE REVIEW

**Comment by paulproteus** [comment]
Hi @kentonv , if you can merge this soon, that'll be grand!

**Comment by kentonv** [comment]
Sorry, but when you need me to look at something in a timely manner, you'll need to say something in person or on IM. Notifications on PR threads get auto-filtered into a label that I batch-process...

This change appears to leave `README.md` in a pretty sorry state. That will need to be fixed before I can merge it.

I'm also confused by `mkdocs.yml` is in the top-level directory instead of under `docs`. I can live with that if it's required but it seems odd...

**Comment by paulproteus** [comment]
+1 re: must fix README.md first; I should have checked that out.

mkdocs.yml does want to be at the top level; that's how it finds out which
directory in the project is the docs directory.
​
Can say more later; thanks for the feedback.

**Comment by paulproteus** [comment]
I adjusted `README.md` so it is in (in my opinion) mergeable state now.

Similar to how https://github.com/meteor/meteor points mostly at the docs, I'm attempting to have our `README.md` point mostly at the docs. I kept the bits that I felt were essential (or the bits that were also in the Meteor `README.md`, even if I didn't feel it was essential).

@kentonv happy for your review. If you prefer I can revert `README.md` to the way it was before this pull request, so that changes to that file are a separate pull request.

**Pull request merged**
