### PR TITLE
Implement `sandstorm uninstall`

### PR DESCRIPTION
**Pull request by kentonv**
Closes #2291

### CODE REVIEW

**Comment by paulproteus** [comment]
I almost love this!

**Feedback that is important to me that you address**

- Part of the reason the docs explain how to uninstall Sandstorm is to indicate to people where Sandstorm puts its files. It'd be nice if we could retain the information about that, so that people have a reference to look at when we say that Sandstorm is very tidy.

**Feedback that is lower-priority**

- The install process creates a systemd symlink. On my Debian system, that is: `/etc/systemd/system/multi-user.target.wants/sandstorm.service` Presumably smart to remove that too. @zarvox is that typical and/or are there other places we should look for a symlink to ourselves? Alternatively (smarter) `sandstorm uninstall` could run `sudo systemd disable sandstorm` or something like that.

- I find italics hard to read in our docs, so I recommend using bold, like this:

> To **change settings**

- or not using italics/bold for emphasis in this case.

- I wonder if this would suit the needs of people who need to "just transfer the Sandstorm data to a new server", but I'm just thinking aloud at this point.

The diff seems generally exceedingly reasonable.


**Other notes**

I can't seem to quickly find any info about `systemd disable`:

```bash
paulproteus@slittingmill:~$ systemd disable -h
Excess arguments.
paulproteus@slittingmill:~$ systemd disable --help
Excess arguments.
paulproteus@slittingmill:~$ man systemd-disable
No manual entry for systemd-disable
```

**Comment by zarvox** [comment]
> I can't seem to quickly find any info about systemd disable:

It's `systemctl disable`, not `systemd disable`.

**Comment by zarvox** [comment]
> The install process creates a systemd symlink. On my Debian system, that is: /etc/systemd/system/multi-user.target.wants/sandstorm.service Presumably smart to remove that too. @zarvox is that typical and/or are there other places we should look for a symlink to ourselves? Alternatively (smarter) sandstorm uninstall could run sudo systemd disable sandstorm or something like that.

Running `systemctl disable sandstorm.service` removes this symlink, and this code does so [here](https://github.com/sandstorm-io/sandstorm/pull/2383/files#diff-3d39d92daed96aa7386c4f61fe8782dbR1019)

**Comment by paulproteus** [comment]
Ignore my remark above about `systemd disable`!

**Comment by kentonv** [comment]
> I find italics hard to read in our docs, so I recommend using bold, like this:

I did not write that line -- it was there and emphasized that way before this change.

> Part of the reason the docs explain how to uninstall Sandstorm is to indicate to people where Sandstorm puts its files. It'd be nice if we could retain the information about that, so that people have a reference to look at when we say that Sandstorm is very tidy.

I am not sure I understand what you want here. To avoid "wrong rock syndrome", would you like to take over the docs changes? I could merge just the first two commits for now.

**Comment by paulproteus** [comment]
I'm +1 on you merging this as-is, and me eventually making the changes I suggest, then!

TIL http://workingsmarter.typepad.com/my_weblog/2008/12/bring-me-a-different-rock.html , pretty cool concept.

**Comment by paulproteus** [comment]
That is - you should merge your docs change as-is, too, and I can make add-on commits as I feel is important, or not.

**Pull request merged**
