### PR TITLE
Update the first-user-admin-promotion code to account for the new schema

### PR DESCRIPTION
**Pull request by dwrensha**
The first dev user was erroneously becoming an admin.

### CODE REVIEW

**Comment by paulproteus** [comment]
Is the only dangerous (historic) instance of `devName`? Just thought I'd ask for a grep.

**Comment by dwrensha** [comment]
I grepped. The only other uses are in migrations.js and in some inaccessible code in accounts-merge-server.js.

**Comment by paulproteus** [comment]
Yay, thanks!

**Comment by paulproteus** [comment]
Argh wrong button. Meant to click **Comment** not **Close and comment**!

**Comment by dwrensha** [comment]
(The test failed the first time with an error about a grain title. I think that indicates some slight lurking flakiness in the tests.)

**Pull request merged**
