### PR TITLE
more context links to tutorials

### PR DESCRIPTION
**Pull request by techtonik**

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by techtonik** [comment]
Everything that is M to .md files is safe to build.

**Comment by kentonv** [comment]
@paulproteus please review, thanks.

**Comment by paulproteus** [comment]
Thanks. I will review this carefully on Monday.

**Comment by paulproteus** [comment]
Hi, thanks @techtonik . I'm going to merge this, and then add an extra commit which I think improves clarity even further.

**Comment by paulproteus** [comment]
Thanks @techtonik ; you can see your changes, with some further modifications, online now: https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial/

I appreciate your willingness to make changes to the docs and would be happy to review/merge any future docs pull requests from you. Let me know if you have any feedback on the addition I made on top of your proposed changes.

**Pull request merged**
