### PR TITLE
Whitelist Mercurial headers in web sessions

### LINKED ISSUE #1897: Feature Request: Whitelist Mercurial HTTP headers
I would like to package Mercurial as a Sandstorm app.  The Mercurial wire protocol sends most of its data using HTTP headers.  They follow the pattern `X-HgArg-N`, where `N` is an integer greater than zero.  Each header payload will be ~1KB by default, so you can pick an upper bound on how high you want N to be.

(I tried hacking around this by disabling this mode of operation, but it blows out the URL length quickly, and it doesn't appear to have a retry mechanism.)

### PR DESCRIPTION
**Pull request by zombiezen**
Fixes #1897

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by paulproteus** [comment]
Garply, ok to test

**Comment by paulproteus** [comment]
Ross, do you happen to know if 16 is the max number of headers that the
Mercurial client sends? If that's not a maximum, then we'll probably
confuse it by accepting only the first 16 and dropping the rest.

Thanks for writing this!

**Comment by zombiezen** [comment]
AFAICT, it's unbounded ([source](https://selenic.com/hg/file/87d4a6c5567e/mercurial/httppeer.py#l128)).  However, it does seem like [newer clients](https://www.mercurial-scm.org/pipermail/mercurial-devel/2016-March/080830.html) may start supporting using POST body as arguments, but this will take a while to get to all downstream package repos etc.

I picked 16 as 16KB seems to be a common header size limit (at least for [IIS](https://www.mercurial-scm.org/wiki/HgWebInIisOnWindows)).  The size of the header payload appears to be proportional to the number of "heads" -- leaf nodes in the history DAG.  For most repositories, this will be only a few.

**Comment by kentonv** [comment]
Maybe we should extend the header whitelist to support a trailing wildcard? Wouldn't be too hard...

**Comment by paulproteus** [comment]
Kenton, I think your idea is a fine one. Ross, are you possibly interested
in looking at the C++ changes needed to implement it? If not, then we
should figure out the best way to support hg within grains. Let me know.

**Comment by zombiezen** [comment]
I'm not entirely sure how to compile/test this myself, but this should be the general patch.

**Comment by kentonv** [comment]
Thanks!

**Pull request merged**
