### PR TITLE
Add CLI for configuring ACME and use it in installer script

### PR DESCRIPTION
**Pull request by kentonv**
Currently the CLI doesn't support directly setting certificates but that would be easy for someone to add. I'm out of time this weekend, though.

### CODE REVIEW

**Comment by kentonv** [comment]
Once this is released, new installs will no longer use globalsign. After a short period to let things settle, we can remove all the globalsign code.

**Comment by kentonv** [comment]
Whoops I broke the build because I apparently fixed a linter error. Will correct shortly.

**Comment by kentonv** [comment]
@ocdtrekkie We should now update the docs to tell people how to configure TLS from the command line, for non-sandcats.

Would also be nice to update the installer to automate some of that, perhaps.

**Comment by ocdtrekkie** [comment]
Yeah, I have this thread in my inbox still so I can review it and look at next steps for docs and such. 👍

**Pull request merged**
