### PR TITLE
Add missing word ("it")

### PR DESCRIPTION
**Pull request by Pistos**

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by paulproteus** [comment]
Hi @PIstos,

Thanks for this fix! I'll get it into the live docs now. I appreciate your attention to detail.

**Comment by Pistos** [comment]
@paulproteus Happy to help.  I'm just another Internet traveller wandering through.  :)  Sandstorm looks/sounds interesting enough, and I'm pondering building a package for my web app project.

**Comment by paulproteus** [comment]
Cool. For what it's worth, if you want any help building that package, I'd love to help you. Or if you want to do something like video chat, or text chat, if you have questions about these docs, then I'd love to dedicate some time to that. I'm asheesh@sandstorm.io; feel free to drop me an email.

Having more apps available within Sandstorm is a high priority for me, and feedback on the docs helps with that, and helping you with any packaging questions you have helps with that, so I hope you'll consider me a resource.

**Comment by paulproteus** [comment]
Merging because this PR is 100% docs.

**Comment by paulproteus** [comment]
This docs change is now live! Thanks again @Pistos !

**Comment by Pistos** [comment]
@paulproteus I appreciate your offer.  IRC will probably work best.  I've pinged you on Freenode.

**Pull request merged**
