### PR TITLE
New icons: share access, app market, report issue, pronoun, source

### PR DESCRIPTION
**Pull request by neynah**
@zarvox

### CODE REVIEW

**Comment by kentonv** [comment]
I think you should overwrite share.svg -- it's not used for anything else.

**Comment by neynah** [comment]
Overwritten! Thanks.

**Comment by ocdtrekkie** [comment]
I feel like bug.svg has some oddities on the right side. On the inside of the bug's body, near the middle leg, there is a weird thickness thing. And another one on the bottom right leg.

**Comment by neynah** [comment]
@ocdtrekkie Here's a close-up. The thickness of the legs should be the same.

Maybe this will help identify what's wrong with it.

bugcloseup

**Comment by ocdtrekkie** [comment]
Your PNG definitely looks much nicer than the SVG render I'm getting from Firefox.

**Comment by ocdtrekkie** [comment]
This is how my Firefox is rendering it:

weirdbug

That being said, as long as the Sandstorm build process renders it correctly, I suppose that's what matters.

**Comment by kentonv** [comment]
We actually switched to shipping SVG to the browser. However, this icon will be so small that I don't think you'll ever see the weirdness. :)

**Pull request merged**
