### PR TITLE
spk.c++: Fixed typo in content string

### PR DESCRIPTION
**Pull request by elimisteve**

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by paulproteus** [comment]
Garply, ok to test

**Comment by paulproteus** [comment]
I'm +1 on this pull request. @kentonv please review/merge this string typo fix.

**Comment by paulproteus** [comment]
```
npm ERR! fetch failed https://registry.npmjs.org/fibers/-/fibers-1.0.5.tgz
npm ERR! Error: 400 Bad Request
npm ERR!     at WriteStream.<anonymous> (/var/lib/jenkins/.meteor/packages/meteor-tool/.1.1.10.hexeji++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/lib/utils/fetch.js:58:12)
```

from the test suite, which is nonsense

**Comment by paulproteus** [comment]
Garply, retest this please

**Pull request merged**
