### PR TITLE
Apply membrane to supervisor's powerbox capabilities

### PR DESCRIPTION
**Pull request by jparyani**

### CODE REVIEW

**Comment by kentonv** [comment]
Can you push your latest changes for me to look at?

**Comment by jparyani** [comment]
Done. See 02872b4

**Comment by zenhack** [comment]
Is this still relevant? Not a lot of context on what this change was even about, and it's a large patch with conflicts now.

**Comment by ocdtrekkie** [comment]
Yeah, I don't even understand what this does/is for.

**Comment by zenhack** [comment]
I think we should close this unless and until someone has new insights as to what this is.

**Pull request closed without merging**
